export default [
  ['How many squares are on a chessboard?', '64', '81', '100', '48', 'A chessboard is 8 × 8. Legend says its inventor asked for rice: one grain on the first square, doubling every square. That would be more rice than exists on Earth.'],
  ['In chess, which piece can jump over other pieces?', 'Knight', 'Bishop', 'King', 'Queen', 'The knight moves in an L-shape: two squares one way, then one square to the side.'],
  ['How many cards are in a standard deck, without jokers?', '52', '54', '48', '50', 'Four suits of 13 cards. Some say it mirrors the 52 weeks in a year.'],
  ['On the classic US Monopoly board, which is the most expensive property?', 'Boardwalk', 'Park Place', 'Marvin Gardens', 'Pennsylvania Avenue', 'The US board is based on Atlantic City. On the UK board, the most expensive square is Mayfair.'],
  ['In English-language Scrabble, how many points is the letter Q worth?', '10', '8', '5', '12', 'Q and Z are both worth 10. There\'s only one Q tile in the bag.'],
  ['How many tiles does each player hold in Scrabble?', '7', '5', '8', '10', 'Using all seven tiles in one turn is called a "bingo" and earns a 50-point bonus.'],
  ['How many dominoes are in a standard double-six set?', '28', '24', '36', '32', 'Every possible pair of numbers from 0 to 6 appears exactly once.'],
  ['In poker, what is the best possible hand?', 'Royal flush', 'Four of a kind', 'Flush', 'Full house', 'A royal flush is A, K, Q, J and 10 of the same suit. The odds of being dealt one in five cards are about 1 in 650,000.'],
  ['Which ancient strategy game, from China, uses black and white stones on a 19 × 19 grid?', 'Go', 'Mahjong', 'Xiangqi', 'Othello', 'In 2016, the program AlphaGo beat top player Lee Sedol, a milestone many experts thought was years away.'],
  ['In Cluedo (called Clue in North America), what three things must players work out?', 'Who, with what weapon, and in which room', 'The murderer, the motive and the time', 'The victim, the weapon and the time', 'The room, the time and the motive', 'The game was invented in England in the 1940s by Anthony Pratt.'],
  ['How many dots are there in total on a standard six-sided die?', '21', '18', '24', '36', '1 + 2 + 3 + 4 + 5 + 6 = 21.'],
  ['On a standard die, what do opposite faces always add up to?', '7', '6', '8', '12', '1 is opposite 6, 2 opposite 5, and 3 opposite 4.'],
  ['In which card game do players try to get as close to 21 as possible without going over?', 'Blackjack', 'Poker', 'Rummy', 'Baccarat', 'Blackjack is also called "twenty-one". An ace plus a 10-value card is a "blackjack".'],
  ['In chess, what is it called when a pawn reaches the far side of the board and becomes another piece?', 'Promotion', 'Castling', 'En passant', 'Checkmate', 'Pawns are usually promoted to a queen, but a player can choose a rook, bishop or knight.'],
  ['What is the game of checkers called in the UK?', 'Draughts', 'Halma', 'Nine men\'s morris', 'Backgammon', 'The name comes from an old word meaning "to draw" or move pieces.'],
  ['In chess, which special move lets the king and a rook move at the same time?', 'Castling', 'En passant', 'Promotion', 'Fork', 'It\'s only allowed if neither piece has moved and the king isn\'t in check or passing through an attacked square.'],
  ['How many cards does each player start with in UNO?', '7', '5', '8', '10', 'UNO was invented in 1971 by Merle Robbins, a barber from Ohio. "Uno" means "one" in Spanish and Italian.'],
  ['Which strategy board game is about conquering territories on a map of the world?', 'Risk', 'Diplomacy', 'Stratego', 'Ticket to Ride', 'Risk was invented in France in 1957 by filmmaker Albert Lamorisse, under the name "La Conquête du Monde".'],
  ['Snakes and Ladders originated in which country?', 'India', 'England', 'China', 'Egypt', 'The original game, Moksha Patam, taught moral lessons: ladders were virtues and snakes were vices.'],
  ['In a standard deck of cards, which king is nicknamed the "suicide king"?', 'King of hearts', 'King of spades', 'King of clubs', 'King of diamonds', 'He appears to be stabbing himself in the head with his sword. The king of hearts is also the only king without a mustache.'],
  ['Which Chinese tile game is usually played with about 144 tiles?', 'Mahjong', 'Dominoes', 'Go', 'Rummikub', 'Mahjong tiles include suits of dots, bamboo and characters, plus winds, dragons, flowers and seasons.'],
  ['In classic Monopoly, how much money do you collect for passing GO?', '$200', '$100', '$500', '$150', 'Monopoly was based on "The Landlord\'s Game", created by Lizzie Magie in 1904 to show the dangers of monopolies.'],
  ['Who beat Boris Spassky in 1972 to become world chess champion?', 'Bobby Fischer', 'Garry Kasparov', 'Anatoly Karpov', 'Mikhail Tal', 'The match in Reykjavík, at the height of the Cold War, was called "the Match of the Century".'],
  ['Which IBM computer defeated world chess champion Garry Kasparov in 1997?', 'Deep Blue', 'Watson', 'AlphaZero', 'HAL 9000', 'Kasparov had beaten an earlier version in 1996. Watson later won the TV quiz show "Jeopardy!" in 2011.'],
  ['In backgammon, how many checkers does each player have?', '15', '12', '16', '10', 'Backgammon is one of the oldest board games, with roots in games played thousands of years ago in Mesopotamia and Persia.'],
  ['Which tile-laying board game is named after a medieval walled city in France?', 'Carcassonne', 'Avignon', 'Mont-Saint-Michel', 'Chambord', 'Carcassonne won Germany\'s "Spiel des Jahres" (Game of the Year) award in 2001.'],
  ['In which game do players drop discs into a grid, trying to get four in a row?', 'Connect Four', 'Othello', 'Tic-tac-toe', 'Battleship', 'Connect Four was mathematically "solved" in 1988: with perfect play, the first player can always win.'],
  ['How many different resource types are there in the board game Catan?', '5', '4', '6', '3', 'Brick, lumber, wool, grain and ore. The game, first released as "The Settlers of Catan" in 1995, was invented by Klaus Teuber.'],
  ['How many players are needed for a standard game of bridge?', '4', '2', '3', '6', 'Bridge is played by two partnerships of two, sitting opposite each other.'],
  ['In chess, what is a "stalemate"?', 'A draw where the player to move has no legal moves but isn\'t in check', 'A win by trapping the king', 'A move where two pieces are captured', 'A loss for running out of time', 'Stalemate ends the game in a draw, which can save a player who is far behind.'],
  ['Which is the most powerful piece in chess?', 'Queen', 'King', 'Rook', 'Bishop', 'The queen can move any number of squares in a straight line. In medieval chess, it could only move one square diagonally.'],
  ['How many pieces does each player start with in chess?', '16', '12', '18', '20', 'Each side has 8 pawns, 2 rooks, 2 knights, 2 bishops, a queen and a king.'],
  ['How many squares are on a Scrabble board?', '225', '196', '256', '144', 'The board is 15 by 15. The center square is a double-word score.'],
  ['How many railroad (station) spaces are on a classic Monopoly board?', '4', '2', '3', '6', 'In the US version they include Reading Railroad and the B&O. In the UK version they\'re London stations, like King\'s Cross.'],
  ['In checkers, what happens when a piece reaches the far side of the board?', 'It becomes a king', 'It is removed', 'It becomes a queen', 'The game ends', 'A king can move backwards as well as forwards.'],
  ['In chess notation, what does "O-O" mean?', 'Kingside castling', 'Queenside castling', 'Check', 'Checkmate', 'Queenside castling is written "O-O-O", and checkmate is shown with "#".'],
  ['How many cards are in a standard tarot deck?', '78', '52', '64', '56', 'It has 22 major arcana and 56 minor arcana. Tarot began as a card game in 15th-century Italy.'],
  ['In Scrabble, how many bonus points do you get for using all seven of your tiles in one turn?', '50', '25', '100', '35', 'The bonus is added on top of the word\'s normal score.'],
  ['In which game do you sink your opponent\'s fleet by calling out grid squares?', 'Battleship', 'Stratego', 'Risk', 'Othello', 'It was played with pencil and paper for decades before it became a plastic board game in 1967.'],
  ['Othello is a trademarked version of which older game?', 'Reversi', 'Go', 'Mancala', 'Checkers', 'Pieces are black on one side and white on the other, and flip when trapped between the opponent\'s pieces.'],
  ['In chess, which piece moves straight forward but captures diagonally?', 'Pawn', 'Bishop', 'Knight', 'King', 'On its first move, a pawn may advance two squares. It can also capture "en passant".'],
  ['In mancala games, what do players move around the board?', 'Seeds or stones', 'Cards', 'Dice', 'Letter tiles', 'Mancala games are among the oldest known board games and have been played across Africa for centuries.'],
  ['Which game uses a "doubling cube"?', 'Backgammon', 'Poker', 'Yahtzee', 'Monopoly', 'Either player can offer to double the stakes; the other must accept or give up the game.'],
  ['How many dice do you roll in Yahtzee?', '5', '6', '3', '4', 'A "Yahtzee" is all five dice showing the same number, worth 50 points.'],
  ['In poker, which hand ranks higher?', 'A flush', 'A straight', 'They\'re equal', 'It depends on the suits', 'A flush is rarer than a straight, so it ranks higher. A full house beats both.'],
];
