export default [
  ['How many bones are in the adult human body?', '206', '186', '212', '250', 'Babies are born with around 270–300 bones. Many fuse together as we grow.'],
  ['What is the largest organ of the human body?', 'Skin', 'Liver', 'Brain', 'Lungs', 'An adult\'s skin covers roughly 2 square meters.'],
  ['Which blood type is known as the universal donor?', 'O negative', 'AB positive', 'A negative', 'B positive', 'O negative red cells can be given to almost anyone, so hospitals use them in emergencies. AB positive people are universal recipients.'],
  ['What is the smallest bone in the human body?', 'Stapes (in the ear)', 'Coccyx', 'Hyoid', 'Patella', 'The stapes is about 3 mm long and passes sound vibrations to the inner ear.'],
  ['Which organ produces insulin?', 'Pancreas', 'Liver', 'Kidneys', 'Stomach', 'Insulin lets cells take in sugar from the blood. In type 1 diabetes, the pancreas stops making it.'],
  ['What is the longest bone in the human body?', 'Femur', 'Tibia', 'Humerus', 'Fibula', 'The femur, or thigh bone, is about a quarter of a person\'s height.'],
  ['How many teeth does a typical adult have, including wisdom teeth?', '32', '28', '30', '36', 'Adults have 32 teeth including four wisdom teeth. Children have 20 baby teeth.'],
  ['Which organs filter the blood to make urine?', 'Kidneys', 'Liver', 'Bladder', 'Spleen', 'Your kidneys filter about 180 liters of fluid a day, but only around 1–2 liters leave as urine.'],
  ['Which protein gives red blood cells their color?', 'Hemoglobin', 'Melanin', 'Keratin', 'Collagen', 'Hemoglobin contains iron, which grabs oxygen and gives blood its red color.'],
  ['What is the heaviest internal organ?', 'Liver', 'Lungs', 'Heart', 'Brain', 'An adult liver weighs about 1.5 kg and can regrow after part of it is removed.'],
  ['Where in the body is the cornea?', 'Eye', 'Ear', 'Heart', 'Knee', 'The cornea is the clear front window of the eye. It has no blood vessels and takes oxygen straight from the air.'],
  ['Which muscle below the lungs is essential for breathing?', 'Diaphragm', 'Abdominals', 'Pectorals', 'Trapezius', 'Hiccups are sudden, involuntary spasms of the diaphragm.'],
  ['How many chambers does the human heart have?', '4', '2', '3', '6', 'Two atria receive blood, and two ventricles pump it out to the lungs and the rest of the body.'],
  ['What is the most common blood type worldwide?', 'O positive', 'A positive', 'B positive', 'AB negative', 'Blood types vary by region, but O positive is the most common overall. AB negative is among the rarest.'],
  ['What is the patella better known as?', 'Kneecap', 'Shoulder blade', 'Collarbone', 'Shin bone', 'The kneecap sits inside a tendon, which protects the knee joint and helps the thigh muscles work.'],
  ['A lack of which vitamin causes scurvy?', 'Vitamin C', 'Vitamin D', 'Vitamin B12', 'Vitamin A', 'Sailors got scurvy on long voyages. British ships began carrying citrus juice, which earned them the nickname "limeys".'],
  ['Which part of the brain is mainly responsible for balance and coordination?', 'Cerebellum', 'Cerebrum', 'Hippocampus', 'Medulla', 'The cerebellum, at the back of the brain, contains more than half of all the brain\'s neurons.'],
  ['What do the alveoli in your lungs do?', 'Exchange oxygen and carbon dioxide', 'Produce mucus', 'Pump air', 'Filter dust', 'Your lungs hold hundreds of millions of these tiny air sacs. Oxygen passes into the blood and CO₂ passes out.'],
  ['Which tissue connects muscle to bone?', 'Tendon', 'Ligament', 'Cartilage', 'Nerve', 'Tendons link muscle to bone, while ligaments link bone to bone.'],
  ['What is a normal resting heart rate for an adult?', '60–100 beats per minute', '20–40 beats per minute', '120–160 beats per minute', '200–220 beats per minute', 'Very fit athletes can have resting heart rates as low as about 40 beats per minute.'],
  ['The olfactory system is responsible for which sense?', 'Smell', 'Taste', 'Hearing', 'Touch', 'Much of what we call "taste" is actually smell, which is why food seems bland when you have a cold.'],
  ['What is the hardest substance in the human body?', 'Tooth enamel', 'Bone', 'Fingernails', 'Cartilage', 'Enamel is harder than bone, but it can\'t grow back once it\'s damaged.'],
  ['What does the hippocampus mainly help with?', 'Forming memories', 'Vision', 'Digestion', 'Balance', 'Its name comes from the Greek for "seahorse", because of its curved shape.'],
  ['Which organ stores bile?', 'Gallbladder', 'Liver', 'Pancreas', 'Stomach', 'The liver makes bile. The gallbladder stores it and releases it to help digest fats.'],
  ['What is the colored part of the eye called?', 'Iris', 'Pupil', 'Retina', 'Lens', 'The iris is a ring of muscle that changes the size of the pupil. Iris patterns are unique enough to be used for ID scans.'],
  ['Roughly what share of an adult\'s body is water?', 'About 60%', 'About 30%', 'About 45%', 'About 85%', 'Newborn babies are about 75% water, and the share falls as we age.'],
  ['What is the largest artery in the human body?', 'Aorta', 'Carotid artery', 'Femoral artery', 'Pulmonary artery', 'The aorta carries oxygen-rich blood out of the heart\'s left ventricle to the rest of the body.'],
  ['How many pairs of chromosomes do humans normally have?', '23', '46', '21', '24', 'That\'s 46 in total, one set from each parent. The 23rd pair (XX or XY) is the sex chromosomes.'],
  ['Hepatitis is an inflammation of which organ?', 'Liver', 'Heart', 'Kidneys', 'Lungs', 'The word comes from the Greek "hepar" (liver) plus "-itis" (inflammation). It is often caused by viruses.'],
  ['What is the medical name for the collarbone?', 'Clavicle', 'Scapula', 'Sternum', 'Patella', 'The clavicle is one of the most commonly broken bones, often from falling onto an outstretched arm.'],
  ['Which blood cells fight infections?', 'White blood cells', 'Red blood cells', 'Platelets', 'Nerve cells', 'White blood cells are made in the bone marrow and are the core of the immune system.'],
  ['What is the largest muscle in the human body?', 'Gluteus maximus', 'Deltoid', 'Latissimus dorsi', 'Biceps', 'The gluteus maximus keeps you upright and powers climbing stairs and standing up.'],
  ['What is the main job of platelets?', 'Helping blood clot', 'Carrying oxygen', 'Fighting infection', 'Producing hormones', 'Platelets are tiny cell fragments that clump together to plug damaged blood vessels.'],
  ['Which gland in the neck regulates metabolism?', 'Thyroid', 'Adrenal gland', 'Pituitary gland', 'Pancreas', 'The butterfly-shaped thyroid needs iodine to make its hormones, which is why table salt is often iodized.'],
  ['How many vertebrae are in the human neck?', '7', '5', '12', '9', 'Almost all mammals have seven neck vertebrae, even giraffes.'],
  ['What is the longest nerve in the body, running down the back of the leg?', 'Sciatic nerve', 'Ulnar nerve', 'Vagus nerve', 'Optic nerve', 'It\'s also the widest nerve in the body. Pain along its path is called sciatica.'],
  ['Where are most nutrients from food absorbed?', 'Small intestine', 'Stomach', 'Large intestine', 'Liver', 'The small intestine is several meters long, and tiny finger-like villi give it a huge surface area.'],
  ['What is the outermost layer of the skin called?', 'Epidermis', 'Dermis', 'Hypodermis', 'Cortex', 'The epidermis constantly renews itself, and we shed millions of dead skin cells every day.'],
  ['About how much blood does an average adult have?', 'About 5 liters', 'About 1 liter', 'About 2.5 liters', 'About 10 liters', 'Blood makes up about 7–8% of your body weight.'],
  ['What is the medical name for the shoulder blade?', 'Scapula', 'Clavicle', 'Humerus', 'Sternum', 'The scapula links the upper arm bone (humerus) to the collarbone (clavicle).'],
  ['Which hormone triggers the "fight or flight" response?', 'Adrenaline', 'Insulin', 'Oxytocin', 'Serotonin', 'Made by the adrenal glands on top of the kidneys, adrenaline speeds up your heart and breathing in moments of stress.'],
  ['Which hormone helps regulate sleep and is released in darkness?', 'Melatonin', 'Cortisol', 'Adrenaline', 'Insulin', 'Melatonin is made by the pineal gland in the brain. Bright light, especially blue light, holds it back.'],
  ['Which protein are hair and nails mainly made of?', 'Keratin', 'Collagen', 'Melanin', 'Hemoglobin', 'Keratin is also what makes up animal horns, hooves, claws and feathers.'],
  ['Which part of the brain regulates body temperature, hunger and thirst?', 'Hypothalamus', 'Thalamus', 'Amygdala', 'Cerebellum', 'Although it\'s only about the size of an almond, the hypothalamus also controls the pituitary gland.'],
  ['How many bones are in the human hand, including the wrist?', '27', '19', '32', '21', 'Eight wrist bones (carpals), five palm bones (metacarpals) and 14 finger bones (phalanges).'],
  ['What is the medical name for the voice box?', 'Larynx', 'Pharynx', 'Trachea', 'Esophagus', 'The vocal cords sit inside the larynx. The "Adam\'s apple" is part of its cartilage.'],
  ['Which vitamin is essential for blood clotting?', 'Vitamin K', 'Vitamin C', 'Vitamin D', 'Vitamin A', 'The "K" comes from the German word "Koagulation". Leafy greens are a good source.'],
  ['What are the three tiny bones of the middle ear?', 'Malleus, incus and stapes', 'Radius, ulna and humerus', 'Tibia, fibula and femur', 'Atlas, axis and coccyx', 'They\'re also called the hammer, anvil and stirrup, after their shapes.'],
  ['Which organ produces bile?', 'Liver', 'Gallbladder', 'Pancreas', 'Spleen', 'A classic trap: the liver makes bile, and the gallbladder only stores it.'],
  ['What is the tube that carries food from the throat to the stomach?', 'Esophagus', 'Trachea', 'Larynx', 'Duodenum', 'Food doesn\'t just fall down it: muscle waves push it along, which is why you can swallow even upside down.'],
  ['In which organ are the islets of Langerhans found?', 'Pancreas', 'Liver', 'Kidney', 'Brain', 'These clusters of cells make insulin and other hormones that control blood sugar.'],
  ['Which nerve carries signals from the eye to the brain?', 'Optic nerve', 'Vagus nerve', 'Auditory nerve', 'Sciatic nerve', 'Where the optic nerve leaves the eye there are no light sensors, creating a "blind spot" your brain fills in.'],
  ['Which gland is often called the "master gland"?', 'Pituitary gland', 'Thyroid', 'Adrenal gland', 'Pineal gland', 'The pea-sized pituitary releases hormones that control many other glands, as well as growth.'],
  ['What is the medical name for the shin bone?', 'Tibia', 'Fibula', 'Femur', 'Ulna', 'The thinner fibula runs alongside the tibia. The ulna is in the forearm.'],
  ['Which blood vessels carry blood back to the heart?', 'Veins', 'Arteries', 'Capillaries', 'Lymph vessels', 'Arteries carry blood away from the heart. The pulmonary veins are unusual: they carry oxygen-rich blood.'],
  ['What is the main pigment that gives skin its color?', 'Melanin', 'Keratin', 'Hemoglobin', 'Bilirubin', 'People have about the same number of pigment cells; skin tone depends mostly on how much melanin they make.'],
  ['A lack of which vitamin causes rickets in children?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B12', 'Without vitamin D the body can\'t absorb enough calcium, so bones grow soft and bend.'],
  ['What are the tiny blood vessels between arteries and veins called?', 'Capillaries', 'Alveoli', 'Ventricles', 'Nephrons', 'Capillary walls are only one cell thick, so oxygen and nutrients can pass through them.'],
  ['The appendix is attached to which part of the gut?', 'Large intestine', 'Stomach', 'Small intestine', 'Esophagus', 'It hangs from the cecum, the start of the large intestine. It may act as a reserve of helpful gut bacteria.'],
  ['How many baby (milk) teeth do children usually have?', '20', '24', '28', '32', 'They usually start falling out around age 6 and are replaced by permanent teeth.'],
  ['What is the largest organ of the lymphatic system?', 'Spleen', 'Appendix', 'Thymus', 'Tonsils', 'The spleen filters the blood and removes old red blood cells. People can live without it.'],
  ['Which layer at the back of the eye contains the light-sensing rods and cones?', 'Retina', 'Cornea', 'Lens', 'Pupil', 'Rods work in dim light, while cones see color. Most people have three types of cone.'],
  ['What is the medical name for the tailbone?', 'Coccyx', 'Sacrum', 'Atlas', 'Pelvis', 'The sacrum sits just above it. The atlas is the top vertebra, which holds up the skull.'],
  ['About how long does a red blood cell live?', 'About 120 days', 'About 1 day', 'About 7 days', 'About 10 years', 'Bone marrow makes roughly 2 million new red blood cells every second to replace them.'],
];
