export default [
  ['What is the capital of Japan?', 'Tokyo', 'Osaka', 'Kyoto', 'Hiroshima', 'Tokyo became the capital in 1868. Before that, the emperor\'s capital was Kyoto.'],
  ['What is the capital of Spain?', 'Madrid', 'Barcelona', 'Seville', 'Valencia', 'Madrid sits near the center of Spain and has been the capital since 1561.'],
  ['What is the capital of Germany?', 'Berlin', 'Munich', 'Frankfurt', 'Bonn', 'Bonn was the capital of West Germany. Berlin became the capital of reunified Germany in 1990.'],
  ['What is the capital of Switzerland?', 'Bern', 'Zurich', 'Geneva', 'Basel', 'Officially, Switzerland calls Bern its "federal city" rather than its capital. Zurich is the largest city.'],
  ['What is the capital of Morocco?', 'Rabat', 'Casablanca', 'Marrakesh', 'Fez', 'Casablanca is Morocco\'s largest city, but Rabat is the capital.'],
  ['What is the capital of Nigeria?', 'Abuja', 'Lagos', 'Kano', 'Ibadan', 'Abuja, a planned city in the center of the country, replaced Lagos as the capital in 1991.'],
  ['What is the capital of Vietnam?', 'Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Huế', 'Ho Chi Minh City, formerly Saigon, is Vietnam\'s largest city.'],
  ['What is the capital of Argentina?', 'Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'Buenos Aires means "good airs" or "fair winds" in Spanish.'],
  ['What is the capital of South Korea?', 'Seoul', 'Busan', 'Incheon', 'Daegu', 'About half of South Korea\'s population lives in the Seoul metropolitan area.'],
  ['What is the capital of Portugal?', 'Lisbon', 'Porto', 'Coimbra', 'Faro', 'Much of Lisbon was rebuilt after a devastating earthquake and tsunami in 1755.'],
  ['What is the capital of Kenya?', 'Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Nairobi has a national park inside the city limits, with giraffes and lions in view of the skyscrapers.'],
  ['What is the capital of Pakistan?', 'Islamabad', 'Karachi', 'Lahore', 'Rawalpindi', 'Islamabad was built in the 1960s as a planned capital, replacing Karachi.'],
  ['What is the capital of Peru?', 'Lima', 'Cusco', 'Arequipa', 'Trujillo', 'Lima was founded by the Spanish conquistador Francisco Pizarro in 1535. Cusco was the Inca capital.'],
  ['What is the capital of Iceland?', 'Reykjavík', 'Akureyri', 'Nuuk', 'Tórshavn', 'Reykjavík is the northernmost capital of an independent country. Nuuk is Greenland\'s capital.'],
  ['What is the capital of Poland?', 'Warsaw', 'Kraków', 'Gdańsk', 'Wrocław', 'Warsaw\'s old town was almost totally destroyed in World War II and carefully rebuilt. It\'s now a UNESCO site.'],
  ['What is the capital of Colombia?', 'Bogotá', 'Medellín', 'Cali', 'Cartagena', 'Bogotá sits about 2,600 m above sea level, one of the highest capitals in the world.'],
  ['What is the capital of India?', 'New Delhi', 'Mumbai', 'Kolkata', 'Bangalore', 'New Delhi was inaugurated in 1931 as the capital of British India and stayed the capital after independence. Kolkata was the earlier capital.'],
  ['What is the capital of Saudi Arabia?', 'Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Mecca and Medina are Islam\'s two holiest cities, but the capital is Riyadh.'],
  ['What is the capital of Croatia?', 'Zagreb', 'Split', 'Dubrovnik', 'Zadar', 'Split and Dubrovnik are famous coastal cities, while Zagreb lies inland in the north.'],
  ['What is the capital of Ethiopia?', 'Addis Ababa', 'Asmara', 'Dire Dawa', 'Gondar', 'Addis Ababa means "new flower" and is home to the headquarters of the African Union. Asmara is Eritrea\'s capital.'],
  ['What is the official capital of the Netherlands?', 'Amsterdam', 'The Hague', 'Rotterdam', 'Utrecht', 'Amsterdam is the capital in the constitution, but the government and parliament sit in The Hague.'],
  ['What is the capital of Hungary?', 'Budapest', 'Debrecen', 'Szeged', 'Pécs', 'Budapest was formed in 1873 by joining Buda and Óbuda on one bank of the Danube with Pest on the other.'],
  ['What is the capital of Chile?', 'Santiago', 'Valparaíso', 'Concepción', 'Antofagasta', 'Chile\'s National Congress meets in Valparaíso, but Santiago is the capital.'],
  ['What is the capital of Finland?', 'Helsinki', 'Tampere', 'Turku', 'Oulu', 'Helsinki replaced Turku as the capital in 1812, when Finland was under Russian rule.'],
  ['Which country\'s flag has a red maple leaf in the middle?', 'Canada', 'Switzerland', 'Austria', 'Lebanon', 'Canada adopted the maple leaf flag in 1965.'],
  ['Which country\'s flag is a red circle on a white background?', 'Japan', 'Bangladesh', 'South Korea', 'Indonesia', 'Japan\'s flag is called Hinomaru, "circle of the sun". Bangladesh\'s flag has a red circle on green.'],
  ['How many stars are on the flag of the United States?', '50', '13', '48', '51', 'Each star is a state. The 13 stripes stand for the original 13 colonies.'],
  ['Which country\'s flag features a green cedar tree?', 'Lebanon', 'Canada', 'Cyprus', 'Israel', 'The Lebanese cedar is an ancient symbol of strength, and it is mentioned in the Bible.'],
  ['Which country has the only national flag that doesn\'t have four sides?', 'Nepal', 'Bhutan', 'Switzerland', 'Vatican City', 'Nepal\'s flag is two stacked triangular pennants. Switzerland\'s and the Vatican\'s flags are square.'],
  ['Which country\'s flag features a white dragon?', 'Bhutan', 'China', 'Japan', 'Vietnam', 'Bhutan\'s own name for itself, Druk Yul, means "Land of the Thunder Dragon".'],
  ['Which color is NOT on the French flag?', 'Green', 'Blue', 'White', 'Red', 'The French tricolor has three vertical stripes: blue, white and red.'],
  ['Which country\'s flag shows a white cross on a red square?', 'Switzerland', 'Denmark', 'England', 'Georgia', 'The Swiss flag is square. The Red Cross emblem is the Swiss flag with its colors reversed. Denmark\'s similar flag is rectangular.'],
];
