export default [
  ['What is the capital of Japan?', 'Tokyo', 'Osaka', 'Kyoto', 'Hiroshima', 'Tokyo became the capital in 1868. Before that, the emperor\'s capital was Kyoto.'],
  ['What is the capital of Spain?', 'Madrid', 'Barcelona', 'Seville', 'Valencia', 'Madrid sits near the center of Spain and has been the capital since 1561, apart from a brief spell in Valladolid (1601–1606).'],
  ['What is the capital of Germany?', 'Berlin', 'Munich', 'Frankfurt', 'Bonn', 'Bonn was the capital of West Germany. Berlin became the capital of reunified Germany in 1990.'],
  ['What is the capital of Switzerland?', 'Bern', 'Zurich', 'Geneva', 'Basel', 'Officially, Switzerland calls Bern its "federal city" rather than its capital. Zurich is the largest city.'],
  ['What is the capital of Morocco?', 'Rabat', 'Casablanca', 'Marrakesh', 'Fez', 'Casablanca is Morocco\'s largest city, but Rabat is the capital.'],
  ['What is the capital of Nigeria?', 'Abuja', 'Lagos', 'Kano', 'Ibadan', 'Abuja, a planned city in the center of the country, replaced Lagos as the capital in 1991.'],
  ['What is the capital of Vietnam?', 'Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Huế', 'Ho Chi Minh City, formerly Saigon, is Vietnam\'s largest city.'],
  ['What is the capital of Argentina?', 'Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'Buenos Aires means "good airs" or "fair winds" in Spanish.'],
  ['What is the capital of South Korea?', 'Seoul', 'Busan', 'Incheon', 'Daegu', 'About half of South Korea\'s population lives in the Seoul metropolitan area.'],
  ['What is the capital of Portugal?', 'Lisbon', 'Porto', 'Coimbra', 'Faro', 'Much of Lisbon was rebuilt after a devastating earthquake and tsunami in 1755.'],
  ['What is the capital of Kenya?', 'Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Nairobi has a national park inside the city limits, with giraffes and lions in view of the skyscrapers.'],
  ['What is the capital of Pakistan?', 'Islamabad', 'Karachi', 'Lahore', 'Rawalpindi', 'Islamabad was built in the 1960s as a planned capital. Karachi was the first capital, and nearby Rawalpindi served in between.'],
  ['What is the capital of Peru?', 'Lima', 'Cusco', 'Arequipa', 'Trujillo', 'Lima was founded by the Spanish conquistador Francisco Pizarro in 1535. Cusco was the Inca capital.'],
  ['What is the capital of Iceland?', 'Reykjavík', 'Akureyri', 'Nuuk', 'Tórshavn', 'Reykjavík is the northernmost capital of an independent country. Nuuk is Greenland\'s capital.'],
  ['What is the capital of Poland?', 'Warsaw', 'Kraków', 'Gdańsk', 'Wrocław', 'Warsaw\'s old town was almost totally destroyed in World War II and carefully rebuilt. It\'s now a UNESCO site.'],
  ['What is the capital of Colombia?', 'Bogotá', 'Medellín', 'Cali', 'Cartagena', 'Bogotá sits about 2,600 m above sea level, one of the highest capitals in the world.'],
  ['What is the capital of India?', 'New Delhi', 'Mumbai', 'Kolkata', 'Bangalore', 'New Delhi was inaugurated in 1931 as the capital of British India and stayed the capital after independence. Kolkata was the earlier capital.'],
  ['What is the capital of Saudi Arabia?', 'Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Mecca and Medina are Islam\'s two holiest cities, but the capital is Riyadh.'],
  ['What is the capital of Croatia?', 'Zagreb', 'Split', 'Dubrovnik', 'Zadar', 'Split and Dubrovnik are famous coastal cities, while Zagreb lies inland in the north.'],
  ['What is the capital of Ethiopia?', 'Addis Ababa', 'Asmara', 'Dire Dawa', 'Gondar', 'Addis Ababa means "new flower" and is home to the headquarters of the African Union. Asmara is Eritrea\'s capital.'],
  ['What is the official capital of the Netherlands?', 'Amsterdam', 'The Hague', 'Rotterdam', 'Utrecht', 'Amsterdam is the capital in the constitution, but the government and parliament sit in The Hague.'],
  ['What is the capital of Hungary?', 'Budapest', 'Debrecen', 'Szeged', 'Pécs', 'Budapest was formed in 1873 by joining Buda and Óbuda on one bank of the Danube with Pest on the other.'],
  ['What is the capital of Chile?', 'Santiago', 'Valparaíso', 'Concepción', 'Antofagasta', 'Chile\'s National Congress meets in Valparaíso, but Santiago is the capital.'],
  ['What is the capital of Finland?', 'Helsinki', 'Tampere', 'Turku', 'Oulu', 'Helsinki replaced Turku as the capital in 1812, when Finland was under Russian rule.'],
  ['Which country\'s flag has a red maple leaf in the middle?', 'Canada', 'Switzerland', 'Austria', 'Lebanon', 'Canada adopted the maple leaf flag in 1965.'],
  ['Which country\'s flag is a red circle on a white background?', 'Japan', 'Bangladesh', 'South Korea', 'Indonesia', 'Japan\'s flag is called Hinomaru, "circle of the sun". Bangladesh\'s flag has a red circle on green.'],
  ['How many stars are on the flag of the United States?', '50', '13', '48', '51', 'Each star is a state. The 13 stripes stand for the original 13 colonies.'],
  ['Which country\'s flag features a green cedar tree?', 'Lebanon', 'Canada', 'Cyprus', 'Israel', 'The Lebanese cedar is an ancient symbol of strength, and it is mentioned in the Bible.'],
  ['Which country has the only national flag that doesn\'t have four sides?', 'Nepal', 'Bhutan', 'Switzerland', 'Vatican City', 'Nepal\'s flag is two stacked triangular pennants. Switzerland\'s and the Vatican\'s flags are square.'],
  ['Which country\'s flag features a white dragon?', 'Bhutan', 'China', 'Japan', 'Vietnam', 'Bhutan\'s own name for itself, Druk Yul, means "Land of the Thunder Dragon".'],
  ['Which color is NOT on the French flag?', 'Green', 'Blue', 'White', 'Red', 'The French tricolor has three vertical stripes: blue, white and red.'],
  ['Which country\'s flag shows a white cross on a red square?', 'Switzerland', 'Denmark', 'England', 'Georgia', 'The Swiss flag is square. The Red Cross emblem is the Swiss flag with its colors reversed. Denmark\'s similar flag is rectangular.'],
  ['What is the capital of Mongolia?', 'Ulaanbaatar', 'Almaty', 'Bishkek', 'Hohhot', 'Ulaanbaatar is often called the coldest capital city in the world. Hohhot is in the Chinese region of Inner Mongolia.'],
  ['What has been the capital of Myanmar since 2005?', 'Naypyidaw', 'Yangon', 'Mandalay', 'Bagan', 'Naypyidaw was built from scratch, with roads of up to 20 lanes that are usually almost empty.'],
  ['What is the official (legislative) capital of Sri Lanka?', 'Sri Jayawardenepura Kotte', 'Colombo', 'Kandy', 'Galle', 'Parliament sits in Kotte, while neighboring Colombo is the executive and judicial capital and the largest city.'],
  ['Which city is Bolivia\'s constitutional capital?', 'Sucre', 'La Paz', 'Santa Cruz', 'Cochabamba', 'Sucre is the constitutional capital, but the government sits in La Paz, the highest seat of government in the world.'],
  ['What is the official capital of Tanzania?', 'Dodoma', 'Dar es Salaam', 'Arusha', 'Zanzibar City', 'Dodoma became the capital in 1996, but Dar es Salaam is still the largest city and business hub.'],
  ['What is the official capital of Côte d\'Ivoire (Ivory Coast)?', 'Yamoussoukro', 'Abidjan', 'Bouaké', 'Accra', 'Yamoussoukro has one of the largest churches in the world. Abidjan is the economic capital, and Accra is in Ghana.'],
  ['What is the capital of Bhutan?', 'Thimphu', 'Kathmandu', 'Paro', 'Lhasa', 'Thimphu is one of the few capitals in the world without traffic lights; police officers direct traffic instead.'],
  ['What is the capital of Slovenia?', 'Ljubljana', 'Bratislava', 'Zagreb', 'Maribor', 'Bratislava is Slovakia\'s capital, a common mix-up. The dragon is Ljubljana\'s symbol.'],
  ['What is the capital of Uruguay?', 'Montevideo', 'Buenos Aires', 'Asunción', 'Punta del Este', 'Montevideo is across the Río de la Plata from Buenos Aires. Asunción is Paraguay\'s capital.'],
  ['Which country\'s flag features an AK-47 rifle?', 'Mozambique', 'Angola', 'Zimbabwe', 'Kenya', 'The rifle is crossed with a hoe, over an open book, standing for defense, farming and education.'],
  ['Which country\'s flag is often called the oldest national flag still in use?', 'Denmark', 'United Kingdom', 'France', 'Netherlands', 'According to legend, the Dannebrog fell from the sky during a battle in 1219. It has been documented since the 1300s.'],
  ['What is the capital of Ireland?', 'Dublin', 'Cork', 'Belfast', 'Galway', 'Belfast is the capital of Northern Ireland, which is part of the United Kingdom.'],
  ['What is the capital of Norway?', 'Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Oslo was called Christiania for about 300 years, until 1925.'],
  ['What is the capital of Greece?', 'Athens', 'Thessaloniki', 'Sparta', 'Patras', 'Athens is one of the oldest cities in Europe, with a recorded history of over 3,000 years.'],
  ['What is the capital of Thailand?', 'Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Thais call it Krung Thep. Its full ceremonial name is one of the longest place names in the world.'],
  ['What is the capital of the Philippines?', 'Manila', 'Quezon City', 'Cebu City', 'Davao City', 'Manila is one of the most densely populated cities in the world. Neighboring Quezon City was the capital from 1948 to 1976.'],
  ['What is the capital of Ghana?', 'Accra', 'Kumasi', 'Lagos', 'Abidjan', 'In 1957, Ghana became one of the first sub-Saharan African countries to gain independence from colonial rule.'],
  ['What is the capital of Venezuela?', 'Caracas', 'Maracaibo', 'Bogotá', 'Quito', 'Caracas is the birthplace of Simón Bolívar, who led much of South America to independence.'],
  ['What is the capital of Cuba?', 'Havana', 'Santiago de Cuba', 'San Juan', 'Kingston', 'Old Havana is a UNESCO World Heritage Site, and its streets are famous for 1950s American cars.'],
  ['What is the capital of Romania?', 'Bucharest', 'Budapest', 'Belgrade', 'Sofia', 'Its Palace of the Parliament is one of the largest administrative buildings in the world.'],
  ['What is the capital of Austria?', 'Vienna', 'Salzburg', 'Graz', 'Innsbruck', 'Vienna was the seat of the Habsburg dynasty. Mozart, Beethoven and Freud all lived and worked there.'],
  ['What is the capital of Jamaica?', 'Kingston', 'Montego Bay', 'Port of Spain', 'Nassau', 'Bob Marley\'s former home in Kingston is now a museum. Port of Spain is in Trinidad and Nassau in the Bahamas.'],
  ['What is the capital of Nepal?', 'Kathmandu', 'Pokhara', 'Thimphu', 'Lhasa', 'Thimphu is the capital of Bhutan, and Lhasa is in Tibet, China.'],
  ['As of 2026, what is the capital of Iran?', 'Tehran', 'Isfahan', 'Baghdad', 'Shiraz', 'Tehran sits at the foot of the Alborz mountains. Isfahan was the capital under the Safavid dynasty.'],
];
