export default [
  ['Who directed "Jurassic Park" (1993)?', 'Steven Spielberg', 'James Cameron', 'George Lucas', 'Ridley Scott', 'Its dinosaurs mixed Stan Winston\'s life-size animatronics with groundbreaking computer graphics.'],
  ['In "The Lion King", what is the name of Simba\'s father?', 'Mufasa', 'Scar', 'Rafiki', 'Zazu', 'In the 1994 film, Mufasa was voiced by James Earl Jones, who was also the voice of Darth Vader.'],
  ['Which film features the line "I\'ll be back"?', 'The Terminator', 'Predator', 'RoboCop', 'Die Hard', 'Arnold Schwarzenegger said it in "The Terminator" (1984), directed by James Cameron.'],
  ['What is the name of the coffee shop in "Friends"?', 'Central Perk', 'Java Joe\'s', 'The Grind', 'Monk\'s Café', 'Monk\'s Café, one of the wrong answers, is the diner in "Seinfeld".'],
  ['Who played Jack in "Titanic"?', 'Leonardo DiCaprio', 'Brad Pitt', 'Matt Damon', 'Johnny Depp', '"Titanic" won 11 Oscars, tying the record set by "Ben-Hur".'],
  ['What is the name of Harry Potter\'s owl?', 'Hedwig', 'Errol', 'Pigwidgeon', 'Fawkes', 'Hedwig is a snowy owl. Errol is the Weasleys\' owl, and Fawkes is Dumbledore\'s phoenix.'],
  ['Which film won the very first Oscar for Best Animated Feature?', 'Shrek', 'Toy Story', 'Monsters, Inc.', 'Spirited Away', 'The award was first given in 2002, and "Shrek" beat "Monsters, Inc." to win it.'],
  ['In "Star Wars", who is Luke Skywalker\'s father?', 'Darth Vader', 'Obi-Wan Kenobi', 'Emperor Palpatine', 'Han Solo', 'The twist is revealed in "The Empire Strikes Back" (1980). Vader was once the Jedi Anakin Skywalker.'],
  ['Which TV series is set in the fictional town of Hawkins, Indiana?', 'Stranger Things', 'Twin Peaks', 'Riverdale', 'Dark', '"Stranger Things" premiered on Netflix in 2016 and is set mostly in the 1980s.'],
  ['In "Breaking Bad", what subject does Walter White teach?', 'Chemistry', 'Physics', 'Biology', 'Mathematics', 'Walter is a high-school chemistry teacher in Albuquerque who turns to making methamphetamine.'],
  ['Which Pixar film follows a robot cleaning up an abandoned Earth?', 'WALL-E', 'Big Hero 6', 'Robots', 'The Iron Giant', 'WALL-E stands for Waste Allocation Load Lifter: Earth-Class.'],
  ['Who played the Joker in "The Dark Knight" (2008)?', 'Heath Ledger', 'Joaquin Phoenix', 'Jared Leto', 'Jack Nicholson', 'Heath Ledger won a posthumous Oscar for Best Supporting Actor for the role.'],
  ['In "Game of Thrones", what is the continent where most of the story takes place?', 'Westeros', 'Essos', 'Middle-earth', 'Narnia', 'The show is based on George R. R. Martin\'s book series "A Song of Ice and Fire".'],
  ['Which film features a shark terrorizing Amity Island?', 'Jaws', 'Deep Blue Sea', 'The Meg', 'Open Water', 'Steven Spielberg\'s "Jaws" (1975) is often called the first summer blockbuster.'],
  ['In "The Simpsons", what is the name of the family\'s town?', 'Springfield', 'Shelbyville', 'Quahog', 'South Park', 'Creator Matt Groening chose Springfield partly because it is one of the most common town names in the US.'],
  ['Who directed "Pulp Fiction"?', 'Quentin Tarantino', 'Martin Scorsese', 'Guy Ritchie', 'the Coen brothers', '"Pulp Fiction" (1994) won the Palme d\'Or, the top prize at the Cannes Film Festival.'],
  ['Which hobbit did Elijah Wood play in "The Lord of the Rings"?', 'Frodo Baggins', 'Samwise Gamgee', 'Bilbo Baggins', 'Pippin Took', 'Frodo carries the One Ring to Mount Doom, with his loyal friend Sam at his side.'],
  ['Which Pixar film is set in the Land of the Dead?', 'Coco', 'Soul', 'Onward', 'Up', '"Coco" (2017) is inspired by Mexico\'s Day of the Dead (Día de Muertos).'],
  ['Who played Tony Stark / Iron Man in the Marvel films?', 'Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo', '"Iron Man" (2008) was the film that launched the Marvel Cinematic Universe.'],
  ['"The Office" (US) is set at a paper company branch in which city?', 'Scranton', 'Stamford', 'Pittsburgh', 'Albany', 'The US show is a remake of the British "The Office" created by Ricky Gervais and Stephen Merchant.'],
  ['In "Finding Nemo", what kind of fish is Nemo?', 'Clownfish', 'Blue tang', 'Angelfish', 'Goldfish', 'Real clownfish live among sea anemones, protected from their stings by a coat of mucus. Dory is a blue tang.'],
  ['Which film was the first non-English-language winner of the Best Picture Oscar?', 'Parasite', 'Roma', '1917', 'Amélie', 'Bong Joon-ho\'s Korean film "Parasite" (2019) won four Oscars, including Best Picture and Best Director.'],
  ['Which fictional spy has the code number 007?', 'James Bond', 'Jason Bourne', 'Ethan Hunt', 'Jack Ryan', 'Ian Fleming created James Bond in his 1953 novel "Casino Royale".'],
  ['In "Squid Game", what is the first game the players face?', 'Red Light, Green Light', 'Tug of war', 'Marbles', 'Dalgona candy', 'When it came out in 2021, "Squid Game" became Netflix\'s most-watched series up to that point.'],
  ['Which film was the first ever to gross over $1 billion worldwide?', 'Titanic', 'Jurassic Park', 'Star Wars', 'Independence Day', '"Titanic" passed $1 billion in 1998 and stayed the highest-grossing film until "Avatar" in 2010.'],
  ['Who directed "Titanic" (1997)?', 'James Cameron', 'Steven Spielberg', 'Ridley Scott', 'Ron Howard', 'James Cameron also directed "The Terminator" and "Avatar".'],
  ['In the 1939 film "The Wizard of Oz", what color are Dorothy\'s slippers?', 'Ruby red', 'Silver', 'Gold', 'Emerald green', 'In L. Frank Baum\'s original book the slippers are silver. The film made them red to show off Technicolor.'],
  ['Which actor played Forrest Gump?', 'Tom Hanks', 'Kevin Costner', 'Robin Williams', 'Bill Murray', 'Tom Hanks won Best Actor two years in a row, for "Philadelphia" and then "Forrest Gump".'],
  ['What is the name of the cowboy doll in "Toy Story"?', 'Woody', 'Buzz', 'Jessie', 'Rex', '"Toy Story" (1995) was the first feature film made entirely with computer animation. Tom Hanks voices Woody.'],
  ['Which animated film features the song "Let It Go"?', 'Frozen', 'Tangled', 'Moana', 'Encanto', 'Sung by Idina Menzel, "Let It Go" won the Oscar for Best Original Song.'],
  ['In "The Matrix", which pill does Neo take?', 'The red pill', 'The blue pill', 'The green pill', 'The white pill', 'The red pill reveals the truth; the blue pill would have sent him back to the comfortable illusion.'],
  ['Which TV series follows the aristocratic Crawley family and their servants?', 'Downton Abbey', 'The Crown', 'Bridgerton', 'Peaky Blinders', '"Downton Abbey" was filmed at Highclere Castle in Hampshire, England.'],
  ['In "Friends", what is Ross Geller\'s profession?', 'Paleontologist', 'Archaeologist', 'Chef', 'Actor', 'Ross works at a natural history museum and later teaches paleontology at a university.'],
  ['Which film contains the line "Here\'s looking at you, kid"?', 'Casablanca', 'Gone with the Wind', 'Citizen Kane', 'The Maltese Falcon', 'Humphrey Bogart says it to Ingrid Bergman in "Casablanca" (1942).'],
  ['Ethan Hunt is the hero of which film series?', 'Mission: Impossible', 'The Bourne films', 'James Bond', 'Fast & Furious', 'Tom Cruise has played Ethan Hunt since 1996 and is famous for doing many of his own stunts.'],
  ['In "Shrek", what kind of creature falls in love with Donkey?', 'A dragon', 'A horse', 'A cat', 'A fairy', 'In the first "Shrek" (2001), Dragon guards the castle where Princess Fiona is held.'],
  ['Which TV series follows a crime gang in Birmingham after World War I?', 'Peaky Blinders', 'Boardwalk Empire', 'The Sopranos', 'Gangs of London', 'The Peaky Blinders were a real Birmingham street gang, though the Shelby family in the show is fictional.'],
  ['Who directed "Inception" and "Oppenheimer"?', 'Christopher Nolan', 'Denis Villeneuve', 'David Fincher', 'Ridley Scott', '"Oppenheimer" (2023) won seven Oscars, including Best Picture and Best Director for Nolan.'],
  ['Who directed the Studio Ghibli film "Spirited Away"?', 'Hayao Miyazaki', 'Isao Takahata', 'Makoto Shinkai', 'Mamoru Hosoda', '"Spirited Away" (2001) won the Oscar for Best Animated Feature. Miyazaki co-founded Studio Ghibli.'],
  ['Which Hogwarts house is Harry Potter sorted into?', 'Gryffindor', 'Slytherin', 'Ravenclaw', 'Hufflepuff', 'The Sorting Hat considered putting Harry in Slytherin, but he asked not to go there.'],
  ['In which city is the sitcom "Friends" set?', 'New York', 'Los Angeles', 'Chicago', 'Boston', 'Although set in New York, the show was filmed on a studio set in Burbank, California.'],
];
