export default [
  ['What is the main ingredient of guacamole?', 'Avocado', 'Peas', 'Cucumber', 'Lime', 'Guacamole goes back to the Aztecs. Its name comes from the Nahuatl "ahuacamolli", meaning avocado sauce.'],
  ['Sushi is most associated with which country\'s cuisine?', 'Japan', 'China', 'Korea', 'Thailand', '"Sushi" refers to the vinegared rice, not the fish. Sliced raw fish on its own is sashimi.'],
  ['Which pasta\'s name means "little ears"?', 'Orecchiette', 'Farfalle', 'Penne', 'Fusilli', 'Orecchiette come from Puglia in southern Italy. Farfalle means "butterflies".'],
  ['Which spice is the most expensive by weight?', 'Saffron', 'Vanilla', 'Cardamom', 'Cinnamon', 'Saffron is the hand-picked threads of the crocus flower: about 150,000 flowers make just 1 kg.'],
  ['What is the main ingredient of hummus?', 'Chickpeas', 'Lentils', 'Fava beans', 'Kidney beans', 'Hummus is chickpeas blended with tahini (sesame paste), lemon juice and garlic.'],
  ['Feta cheese comes from which country?', 'Greece', 'Italy', 'Turkey', 'Bulgaria', 'In the EU, only cheese from parts of Greece, made from sheep\'s milk with up to 30% goat\'s milk, can be called feta.'],
  ['Which fruit is traditional cider made from?', 'Apples', 'Pears', 'Grapes', 'Plums', 'The pear version of cider has its own name: perry.'],
  ['Paella comes from which country?', 'Spain', 'Italy', 'Portugal', 'Mexico', 'Paella comes from Valencia, and is named after the wide, shallow pan it\'s cooked in.'],
  ['What is tofu made from?', 'Soybeans', 'Rice', 'Chickpeas', 'Wheat', 'Tofu is made by curdling soy milk and pressing the curds, much like cheese-making.'],
  ['Which nut is the main ingredient of marzipan?', 'Almond', 'Hazelnut', 'Walnut', 'Cashew', 'Marzipan is mostly ground almonds and sugar. Lübeck in Germany and Toledo in Spain are famous for it.'],
  ['Which alcoholic drink is made from fermented honey?', 'Mead', 'Cider', 'Sake', 'Kefir', 'Mead, sometimes called honey wine, is one of the oldest known alcoholic drinks.'],
  ['Which country is the world\'s largest coffee producer?', 'Brazil', 'Colombia', 'Vietnam', 'Ethiopia', 'Brazil has been the top producer for over 150 years and grows roughly a third of the world\'s coffee.'],
  ['Which yellow spice gives many curries their color?', 'Turmeric', 'Saffron', 'Cumin', 'Paprika', 'Turmeric is a root related to ginger, and its bright color comes from a compound called curcumin.'],
  ['Which Italian dish is made of layered pasta sheets, sauce and cheese?', 'Lasagna', 'Risotto', 'Gnocchi', 'Carbonara', 'Lasagna is especially linked to Emilia-Romagna, where it\'s made with ragù and béchamel.'],
  ['Which cheese is traditionally used on a Margherita pizza?', 'Mozzarella', 'Parmesan', 'Cheddar', 'Gorgonzola', 'The red, white and green toppings echo the Italian flag. Legend says the pizza was named after Queen Margherita in 1889.'],
  ['What is a "Granny Smith"?', 'An apple', 'A pear', 'A potato', 'A plum', 'The Granny Smith apple was first grown in Australia in 1868 by Maria Ann Smith.'],
  ['Kimchi is a staple of which country\'s cuisine?', 'Korea', 'Japan', 'China', 'Vietnam', 'The best-known kimchi is napa cabbage fermented with chili, garlic and ginger.'],
  ['Which grain is used to brew traditional Japanese sake?', 'Rice', 'Barley', 'Wheat', 'Millet', 'Sake is often called rice wine, but it\'s brewed in a way closer to beer.'],
  ['What is the main ingredient of a classic gazpacho?', 'Tomato', 'Cucumber', 'Bell pepper', 'Potato', 'Gazpacho is a cold soup from Andalusia in southern Spain.'],
  ['Oranges are well known for being rich in which vitamin?', 'Vitamin C', 'Vitamin A', 'Vitamin D', 'Vitamin K', 'One medium orange covers roughly a full day\'s recommended vitamin C.'],
  ['Which sauce is made from egg yolks, butter and lemon juice?', 'Hollandaise', 'Béchamel', 'Mayonnaise', 'Pesto', 'Hollandaise is one of the classic French "mother sauces" and the topping for eggs Benedict. Mayonnaise uses oil, not butter.'],
  ['Which herb is the base of pesto alla genovese?', 'Basil', 'Parsley', 'Mint', 'Oregano', 'Genoa\'s pesto is basil, pine nuts, garlic, Parmesan, pecorino and olive oil.'],
  ['Poutine is a famous dish from which country?', 'Canada', 'United States', 'France', 'Belgium', 'Poutine comes from Quebec: fries topped with cheese curds and gravy.'],
  ['Which ingredient makes traditional bread dough rise?', 'Yeast', 'Salt', 'Sugar', 'Vinegar', 'Yeast feeds on sugars and releases carbon dioxide, whose bubbles make the dough rise.'],
  ['Which spiky Southeast Asian fruit is famous for its strong smell?', 'Durian', 'Jackfruit', 'Mango', 'Rambutan', 'Durian smells so strong that it\'s banned on public transport in Singapore.'],
  ['Champagne comes from a region of which country?', 'France', 'Italy', 'Spain', 'Germany', 'In the EU, only sparkling wine from the Champagne region in northeastern France can be called Champagne.'],
  ['Pad thai comes from which country?', 'Thailand', 'Vietnam', 'Laos', 'Malaysia', 'Pad thai was promoted as a national dish of Thailand in the 1930s and 1940s.'],
  ['What is Brie?', 'A soft cheese', 'A type of bread', 'A sausage', 'A white wine', 'Brie is named after the Brie region east of Paris, and its white rind is an edible mold.'],
  ['Which country produces the most olive oil?', 'Spain', 'Italy', 'Greece', 'Tunisia', 'Spain usually produces around 40% or more of the world\'s olive oil, much of it in Andalusia.'],
  ['Raisins are dried what?', 'Grapes', 'Plums', 'Figs', 'Dates', 'Dried plums have their own name: prunes.'],
  ['What is the spirit in a classic mojito?', 'White rum', 'Vodka', 'Gin', 'Tequila', 'The mojito comes from Cuba: white rum, sugar, lime, mint and soda water.'],
  ['Which vegetable gives borscht its deep red color?', 'Beetroot', 'Red cabbage', 'Tomato', 'Red pepper', 'Borscht is popular across Eastern Europe. Ukrainian borscht was added to a UNESCO heritage list in 2022.'],
  ['Which pastry is used to make éclairs and profiteroles?', 'Choux pastry', 'Puff pastry', 'Shortcrust pastry', 'Filo pastry', 'Choux pastry puffs up from steam, leaving a hollow inside to fill with cream.'],
  ['Pierogi, filled dumplings, are a national dish of which country?', 'Poland', 'Hungary', 'Greece', 'Portugal', 'Pierogi can be filled with potato and cheese, sauerkraut, meat or fruit.'],
  ['Which spice comes from the inner bark of a tree?', 'Cinnamon', 'Nutmeg', 'Clove', 'Black pepper', 'Cinnamon sticks are curled strips of dried bark. Cloves are flower buds and nutmeg is a seed.'],
  ['Real wasabi is made from what?', 'The grated stem of a plant', 'Green chili peppers', 'Seaweed', 'Mustard seeds', 'Most "wasabi" served outside Japan is actually horseradish, mustard and green coloring.'],
  ['Which cocktail is made with tequila, lime juice and orange liqueur?', 'Margarita', 'Daiquiri', 'Cosmopolitan', 'Mojito', 'The orange liqueur in a margarita is usually triple sec or Cointreau.'],
  ['Which nut is used in Nutella?', 'Hazelnut', 'Almond', 'Peanut', 'Walnut', 'Ferrero launched Nutella in Italy in 1964, based on an older hazelnut spread made when cocoa was scarce.'],
  ['Gouda cheese comes from which country?', 'Netherlands', 'Belgium', 'Switzerland', 'Denmark', 'Gouda is named after the Dutch city of Gouda, where it was traditionally traded.'],
  ['What does "al dente" mean when cooking pasta?', 'Firm to the bite', 'Cooked in the oven', 'Eaten outdoors', 'With extra sauce', '"Al dente" is Italian for "to the tooth". "Al forno" means baked and "al fresco" means outdoors.'],
  ['Which grain is used to make risotto?', 'Rice', 'Barley', 'Wheat', 'Corn', 'Risotto uses starchy short-grain rice such as Arborio or Carnaroli, which makes it creamy.'],
  ['Which compound makes chili peppers taste hot?', 'Capsaicin', 'Caffeine', 'Menthol', 'Piperine', 'Capsaicin triggers the same nerve receptors that sense heat. Piperine is what makes black pepper spicy.'],
];
