export default [
  ['What is the name of Nintendo\'s famous mustached plumber?', 'Mario', 'Luigi', 'Wario', 'Toad', 'Mario first appeared in "Donkey Kong" (1981) as "Jumpman", and he was a carpenter back then.'],
  ['Which block-building game was created by Mojang?', 'Minecraft', 'Roblox', 'Terraria', 'Fortnite', 'Minecraft has sold over 300 million copies, more than any other video game.'],
  ['Which princess does Mario usually rescue?', 'Princess Peach', 'Princess Zelda', 'Princess Daisy', 'Rosalina', 'Peach rules the Mushroom Kingdom. In the West she was called Princess Toadstool until the 1990s.'],
  ['What is the name of the hero you play in "The Legend of Zelda"?', 'Link', 'Zelda', 'Ganon', 'Epona', 'A common mix-up: Zelda is the princess, Link is the hero, and Epona is his horse.'],
  ['Which company created Sonic the Hedgehog?', 'Sega', 'Nintendo', 'Sony', 'Atari', 'Sonic debuted in 1991 as Sega\'s speedy mascot to rival Nintendo\'s Mario.'],
  ['What color is Pac-Man?', 'Yellow', 'Red', 'Blue', 'Green', 'Pac-Man\'s shape was reportedly inspired by a pizza with one slice missing.'],
  ['Which falling-block puzzle game was created by Alexey Pajitnov in the Soviet Union?', 'Tetris', 'Columns', 'Puyo Puyo', 'Dr. Mario', 'Tetris was created in 1984. Its pieces are tetrominoes, each made of four squares.'],
  ['Which yellow electric Pokémon is Ash\'s partner?', 'Pikachu', 'Raichu', 'Pichu', 'Jigglypuff', 'The name mixes Japanese sounds: "pika" (a sparkle) and "chu" (a mouse\'s squeak).'],
  ['In "Among Us", what are the hidden saboteurs called?', 'Impostors', 'Traitors', 'Spies', 'Ghosts', 'Among Us came out in 2018 but became a huge hit in 2020.'],
  ['The fictional city of Los Santos appears in which game series?', 'Grand Theft Auto', 'Saints Row', 'Watch Dogs', 'Mafia', 'Los Santos is the GTA series\' version of Los Angeles.'],
  ['In Fortnite, what is the Battle Bus used for?', 'Dropping players onto the island', 'Healing players', 'Storing loot', 'Ending the match', 'Each match starts with players jumping out of the flying bus and gliding down to the island.'],
  ['Which company makes the Xbox?', 'Microsoft', 'Sony', 'Nintendo', 'Sega', 'The first Xbox launched in 2001.'],
  ['How many Pokémon were in the original first generation?', '151', '150', '100', '251', 'The first games, Pokémon Red and Green, came out in Japan in 1996. Number 151 is Mew.'],
  ['What is the name of Mario\'s brother?', 'Luigi', 'Wario', 'Yoshi', 'Toad', 'Luigi is Mario\'s younger twin brother. He is a little taller and usually wears green.'],
  ['What is the name of the armored hero of the "Halo" series?', 'Master Chief', 'Marcus Fenix', 'Doomguy', 'Commander Shepard', 'Master Chief\'s real name is John-117.'],
  ['In gaming, what does "NPC" stand for?', 'Non-player character', 'New player challenge', 'Next power-up crate', 'Network play connection', 'NPCs are characters controlled by the game itself, like shopkeepers and villagers.'],
  ['Which studio made "The Witcher 3: Wild Hunt"?', 'CD Projekt Red', 'Bethesda', 'BioWare', 'Ubisoft', 'CD Projekt Red is Polish. The Witcher games are based on books by Andrzej Sapkowski.'],
  ['Which Nintendo console, released in 2006, was famous for its motion controls?', 'Wii', 'GameCube', 'Switch', 'Nintendo DS', 'The Wii sold over 100 million units, helped a lot by Wii Sports.'],
  ['In "Angry Birds", what are the birds attacking?', 'Pigs', 'Cats', 'Snakes', 'Monkeys', 'Angry Birds was made by Rovio, a Finnish studio, and launched in 2009.'],
  ['In the 1981 arcade game, which ape throws barrels at Mario?', 'Donkey Kong', 'King Kong', 'Diddy Kong', 'Funky Kong', 'Donkey Kong was designed by Shigeru Miyamoto, who later created The Legend of Zelda too.'],
  ['In which year was the original PlayStation released in Japan?', '1994', '1990', '1997', '2000', 'It launched in Japan in December 1994, then in North America and Europe in 1995.'],
  ['What do you mainly do in "The Sims"?', 'Simulate people\'s everyday lives', 'Race cars', 'Fight aliens', 'Build cities only', 'The Sims was designed by Will Wright, who also created SimCity.'],
  ['What are the names of the four ghosts in Pac-Man?', 'Blinky, Pinky, Inky and Clyde', 'Larry, Moe, Curly and Shemp', 'Red, Blue, Green and Orange', 'Boo, Spook, Ghoul and Wisp', 'Each ghost behaves differently: Blinky chases you directly, while Pinky tries to cut you off from the front.'],
  ['Which battle royale game is made by Epic Games?', 'Fortnite', 'PUBG', 'Apex Legends', 'Call of Duty: Warzone', 'Fortnite\'s Battle Royale mode launched in 2017.'],
  ['What is the name of Sonic\'s two-tailed fox friend?', 'Tails', 'Knuckles', 'Shadow', 'Amy', 'Tails\' real name is Miles Prower, a pun on "miles per hour".'],
  ['Which game series is set in the world of Azeroth?', 'Warcraft', 'The Elder Scrolls', 'Diablo', 'Final Fantasy', 'World of Warcraft, launched in 2004, is set in Azeroth.'],
  ['In "Super Mario", which item makes Mario grow bigger?', 'Super Mushroom', 'Fire Flower', 'Super Star', 'Coin', 'A Fire Flower lets Mario throw fireballs, and a Super Star makes him briefly invincible.'],
  ['Which Japanese company makes the "Final Fantasy" series?', 'Square Enix', 'Capcom', 'Konami', 'Sega', 'The first Final Fantasy came out in 1987 from Square, which merged with Enix in 2003.'],
  ['Which studio develops the main Pokémon games?', 'Game Freak', 'Retro Studios', 'HAL Laboratory', 'Rare', 'Game Freak was founded by Satoshi Tajiri, inspired by his childhood hobby of collecting insects.'],
  ['In Minecraft, what green creature sneaks up and explodes?', 'Creeper', 'Zombie', 'Enderman', 'Slime', 'The Creeper was born from a coding mistake: a pig\'s height and length got swapped, making it tall and thin.'],
  ['Pac-Man was originally released in Japan under which name?', 'Puck-Man', 'Paku-Paku', 'Pizza-Man', 'Munch-Man', 'It was renamed for the US partly because vandals could easily change the "P" in Puck-Man into another letter.'],
  ['Which company developed "Half-Life" and created the Steam store?', 'Valve', 'Blizzard', 'id Software', 'Epic Games', 'Half-Life came out in 1998. Valve launched Steam in 2003, originally to update its own games.'],
  ['In which year was Minecraft first made available to the public, as an early version?', '2009', '2011', '2006', '2013', 'Markus "Notch" Persson released the first version in 2009. The full release came in 2011, and Microsoft bought Mojang in 2014.'],
  ['Who is the main villain in most "Legend of Zelda" games?', 'Ganon (Ganondorf)', 'Bowser', 'Dr. Eggman', 'King K. Rool', 'Bowser is Mario\'s enemy, Dr. Eggman is Sonic\'s and King K. Rool is Donkey Kong\'s.'],
  ['Solid Snake is the hero of which game series?', 'Metal Gear', 'Resident Evil', 'Splinter Cell', 'Hitman', 'The series was created by Hideo Kojima, starting in 1987.'],
  ['Which Japanese studio made "Dark Souls" and "Elden Ring"?', 'FromSoftware', 'Capcom', 'Square Enix', 'Konami', 'FromSoftware\'s games are famous for their difficulty. George R. R. Martin helped create the mythology of "Elden Ring".'],
  ['Lara Croft is the heroine of which game series?', 'Tomb Raider', 'Uncharted', 'Prince of Persia', 'Assassin\'s Creed', 'The first Tomb Raider came out in 1996. Angelina Jolie played Lara in the 2001 film.'],
  ['In Pokémon, which types are super effective against Water types?', 'Grass and Electric', 'Fire and Ground', 'Rock and Steel', 'Ice and Normal', 'Water is strong against Fire, Ground and Rock, but weak to Grass and Electric.'],
  ['Who composed the famous theme music for "Super Mario Bros." and "The Legend of Zelda"?', 'Koji Kondo', 'Nobuo Uematsu', 'Shigeru Miyamoto', 'Yoko Shimomura', 'Nobuo Uematsu is known for the Final Fantasy music. Miyamoto designed the games themselves.'],
  ['Which company made the arcade game "Space Invaders" (1978)?', 'Taito', 'Namco', 'Atari', 'Nintendo', 'Space Invaders was so popular in Japan it was rumored to cause a shortage of 100-yen coins (a popular legend that\'s probably exaggerated).'],
  ['What is the name of the kingdom where most "Legend of Zelda" games take place?', 'Hyrule', 'Mushroom Kingdom', 'Tamriel', 'Azeroth', 'The Mushroom Kingdom belongs to Mario, Tamriel to The Elder Scrolls, and Azeroth to Warcraft.'],
];
