export default [
  ['What is Superman\'s home planet?', 'Krypton', 'Mars', 'Thanagar', 'Apokolips', 'Baby Kal-El was sent to Earth just before Krypton exploded.'],
  ['What is Batman\'s secret identity?', 'Bruce Wayne', 'Clark Kent', 'Peter Parker', 'Tony Stark', 'Batman was created by Bob Kane and Bill Finger and first appeared in 1939. Clark Kent is Superman.'],
  ['What is the name of the original Spider-Man?', 'Peter Parker', 'Miles Morales', 'Bruce Banner', 'Steve Rogers', 'Spider-Man first appeared in 1962, created by Stan Lee and Steve Ditko. Miles Morales came later, in 2011.'],
  ['Which city does Batman protect?', 'Gotham City', 'Metropolis', 'Star City', 'Central City', '"Gotham" was an old nickname for New York City. Metropolis is Superman\'s city.'],
  ['What is the name of Thor\'s home realm?', 'Asgard', 'Midgard', 'Xandar', 'Wakanda', 'In Norse myth, Midgard is the world of humans: Earth.'],
  ['Which hero is nicknamed the "Man of Steel"?', 'Superman', 'Iron Man', 'Batman', 'Captain America', 'Superman first appeared in Action Comics #1 in 1938, often seen as the start of the superhero genre.'],
  ['Which metal is bonded to Wolverine\'s skeleton?', 'Adamantium', 'Vibranium', 'Titanium', 'Uru', 'Wolverine\'s claws are actually bone, coated in adamantium like the rest of his skeleton.'],
  ['In the Marvel films, what is Captain America\'s shield made of?', 'Vibranium', 'Adamantium', 'Steel', 'Titanium', 'In the films, vibranium is a rare metal found in Wakanda.'],
  ['Who turns into the Hulk?', 'Bruce Banner', 'Bruce Wayne', 'Steve Rogers', 'Reed Richards', 'Scientist Bruce Banner became the Hulk after being exposed to gamma radiation.'],
  ['Which villain gathers the Infinity Stones in "Avengers: Infinity War"?', 'Thanos', 'Loki', 'Ultron', 'Red Skull', 'With all six stones, Thanos snaps his fingers and wipes out half of all life in the universe.'],
  ['What is the name of Wonder Woman\'s home island?', 'Themyscira', 'Atlantis', 'Krypton', 'Paradise City', 'Themyscira is home to the Amazons. Wonder Woman\'s real name is Diana.'],
  ['Which publisher created Spider-Man?', 'Marvel', 'DC Comics', 'Image Comics', 'Dark Horse', 'Marvel started out as Timely Comics in 1939 and took the Marvel name in the early 1960s.'],
  ['Which publisher created Batman?', 'DC Comics', 'Marvel', 'Image Comics', 'Dark Horse', 'DC stands for Detective Comics, the magazine where Batman first appeared.'],
  ['Which green crystal weakens Superman?', 'Kryptonite', 'Vibranium', 'Adamantium', 'Unobtainium', 'Kryptonite is radioactive rock from the remains of his home planet, Krypton.'],
  ['What is the name of Black Panther\'s home country?', 'Wakanda', 'Genosha', 'Latveria', 'Sokovia', 'Black Panther first appeared in 1966 and is widely seen as the first Black superhero in mainstream American comics.'],
  ['What is the name of Batman\'s loyal butler?', 'Alfred', 'Jarvis', 'Jeeves', 'Edwin', 'Alfred Pennyworth raised Bruce Wayne after his parents were killed. Jarvis is Tony Stark\'s butler, later his AI.'],
  ['Who co-created Spider-Man, the X-Men and many Marvel heroes with artists like Jack Kirby?', 'Stan Lee', 'Bob Kane', 'Alan Moore', 'Frank Miller', 'Stan Lee made cameo appearances in most Marvel films until his death in 2018.'],
  ['What is the Flash\'s main superpower?', 'Super speed', 'Flight', 'Invisibility', 'Super strength', 'The Flash draws his speed from the "Speed Force". Barry Allen is the best-known Flash.'],
  ['Tony Stark is the secret identity of which hero?', 'Iron Man', 'Captain America', 'Ant-Man', 'Doctor Strange', 'Tony Stark builds his first armored suit while being held captive.'],
  ['What is the real name of the original Green Goblin?', 'Norman Osborn', 'Otto Octavius', 'Eddie Brock', 'Adrian Toomes', 'Otto Octavius is Doctor Octopus, Eddie Brock is Venom and Adrian Toomes is the Vulture.'],
  ['Aquaman is the king of which undersea realm?', 'Atlantis', 'Themyscira', 'Lemuria', 'Rapture', 'Aquaman can breathe underwater and talk to sea creatures.'],
  ['Where does Green Lantern get his powers?', 'A power ring', 'A magic hammer', 'A radioactive spider', 'A super-soldier serum', 'Green Lantern rings run on willpower. Hal Jordan is the best-known Green Lantern.'],
  ['Which Belgian comic hero is a young reporter with a white dog named Snowy?', 'Tintin', 'Spirou', 'Asterix', 'Lucky Luke', 'Tintin first appeared in 1929, and his adventures have been translated into dozens of languages. In French, Snowy is "Milou".'],
  ['Who created Tintin?', 'Hergé', 'René Goscinny', 'Albert Uderzo', 'André Franquin', 'Hergé was the pen name of Georges Remi: his initials, R.G., said aloud in French.'],
  ['In "Asterix", what gives the Gauls their super strength?', 'A magic potion', 'Wild boar meat', 'A sacred ring', 'Mistletoe tea', 'The druid Getafix (Panoramix in French) brews it. Obelix fell into the pot as a baby, so the effect is permanent for him.'],
  ['Which comic strip stars a lasagna-loving orange cat?', 'Garfield', 'Peanuts', 'Calvin and Hobbes', 'Heathcliff', 'Garfield was created by Jim Davis in 1978 and famously hates Mondays.'],
  ['Which comic strip features Charlie Brown and Snoopy?', 'Peanuts', 'Calvin and Hobbes', 'Garfield', 'Dilbert', 'Charles M. Schulz drew Peanuts every day from 1950 to 2000.'],
  ['Who founded the X-Men and leads them from his wheelchair?', 'Professor X', 'Magneto', 'Cyclops', 'Beast', 'Professor Charles Xavier is a powerful telepath. Magneto, his old friend, became his rival.'],
  ['Which line is Spider-Man\'s famous motto?', 'With great power comes great responsibility', 'I am vengeance', 'Avengers, assemble!', 'Up, up and away!', 'The line appears in Spider-Man\'s very first comic in 1962 and is closely tied to his Uncle Ben.'],
  ['Mr. Fantastic, the Invisible Woman, the Human Torch and the Thing form which team?', 'Fantastic Four', 'The Avengers', 'Justice League', 'X-Men', 'The Fantastic Four (1961), by Stan Lee and Jack Kirby, kicked off Marvel\'s age of superheroes.'],
  ['What is Superman\'s Kryptonian birth name?', 'Kal-El', 'Jor-El', 'Zod', 'Kara Zor-El', 'Jor-El is his father, and Kara Zor-El is his cousin, Supergirl.'],
  ['Who created Superman?', 'Jerry Siegel and Joe Shuster', 'Stan Lee and Jack Kirby', 'Bob Kane and Bill Finger', 'Alan Moore and Dave Gibbons', 'Two teenagers from Cleveland came up with him, and sold the rights in 1938 for $130.'],
  ['What is Deadpool\'s real name?', 'Wade Wilson', 'Logan', 'Frank Castle', 'Scott Summers', 'Frank Castle is the Punisher and Scott Summers is Cyclops. Logan is Wolverine.'],
  ['Matt Murdock, a blind lawyer, is the secret identity of which hero?', 'Daredevil', 'The Punisher', 'Moon Knight', 'Iron Fist', 'Matt lost his sight as a boy in an accident with radioactive chemicals, which heightened his other senses.'],
  ['What is the name of the Joker\'s partner, a former psychiatrist?', 'Harley Quinn', 'Poison Ivy', 'Catwoman', 'Talia al Ghul', 'Harley Quinn was created for "Batman: The Animated Series" in 1992 and only later added to the comics.'],
  ['Who wrote the graphic novel "Watchmen"?', 'Alan Moore', 'Frank Miller', 'Neil Gaiman', 'Grant Morrison', 'Illustrated by Dave Gibbons, "Watchmen" (1986–87) is the only graphic novel on Time\'s list of the 100 best novels since 1923.'],
  ['Which friend of Captain America becomes the Winter Soldier?', 'Bucky Barnes', 'Sam Wilson', 'Nick Fury', 'Peggy Carter', 'Sam Wilson, the Falcon, later takes up the shield as Captain America himself.'],
  ['Monkey D. Luffy is the hero of which manga?', 'One Piece', 'Naruto', 'Dragon Ball', 'Bleach', 'Created by Eiichiro Oda, One Piece has sold over 500 million copies, the best-selling manga ever.'],
  ['What is Black Widow\'s real name?', 'Natasha Romanoff', 'Wanda Maximoff', 'Carol Danvers', 'Jean Grey', 'Wanda Maximoff is the Scarlet Witch, Carol Danvers is Captain Marvel and Jean Grey is from the X-Men.'],
  ['In which New York borough did Peter Parker grow up?', 'Queens', 'Brooklyn', 'Manhattan', 'The Bronx', 'Peter grew up in Forest Hills, Queens, with his Aunt May and Uncle Ben.'],
  ['Which Franco-Belgian comic hero is "the man who shoots faster than his shadow"?', 'Lucky Luke', 'Tintin', 'Spirou', 'Blueberry', 'Lucky Luke was created by Morris in 1946, and René Goscinny of Asterix fame later wrote many of the stories.'],
];
