export default [
  ['In which city is the Eiffel Tower?', 'Paris', 'Lyon', 'Brussels', 'Marseille', 'The tower is about 330 m tall. It was meant to be temporary, but it was kept partly because it was useful as a radio antenna.'],
  ['In which Indian city is the Taj Mahal?', 'Agra', 'Delhi', 'Jaipur', 'Mumbai', 'Emperor Shah Jahan built it in the mid-1600s as a tomb for his wife, Mumtaz Mahal.'],
  ['In which city is the Colosseum?', 'Rome', 'Athens', 'Naples', 'Milan', 'The Colosseum hosted gladiator fights and public shows for centuries.'],
  ['In which city is the Sagrada Família basilica?', 'Barcelona', 'Madrid', 'Seville', 'Valencia', 'Construction began in 1882, and as of 2026 the basilica is still not completely finished.'],
  ['Which architect designed the Sagrada Família?', 'Antoni Gaudí', 'Le Corbusier', 'Gustave Eiffel', 'Frank Gehry', 'Gaudí worked on it for over 40 years and is buried in its crypt.'],
  ['In which country is Petra, the ancient city carved into rock?', 'Jordan', 'Egypt', 'Israel', 'Saudi Arabia', 'Petra was the capital of the Nabataeans and is famous for the Treasury, carved into pink sandstone.'],
  ['The Christ the Redeemer statue overlooks which city?', 'Rio de Janeiro', 'São Paulo', 'Lisbon', 'Buenos Aires', 'The statue is about 30 m tall, stands on Corcovado mountain and was completed in 1931.'],
  ['Which landmark was built as the entrance to the 1889 World\'s Fair in Paris?', 'The Eiffel Tower', 'The Arc de Triomphe', 'The Statue of Liberty', 'The Atomium', 'Gustave Eiffel\'s company built it in about two years. Many Parisian artists protested against it at the time.'],
  ['"Big Ben" is the nickname of what?', 'The great bell of the clock tower at Westminster', 'A bridge in London', 'A royal palace', 'A famous ship', 'The tower itself was renamed Elizabeth Tower in 2012 for Queen Elizabeth II\'s Diamond Jubilee.'],
  ['In which city is the Brandenburg Gate?', 'Berlin', 'Munich', 'Vienna', 'Hamburg', 'Completed in 1791, the gate became a symbol of German reunification after the Berlin Wall fell.'],
  ['In which country is Angkor Wat?', 'Cambodia', 'Thailand', 'Vietnam', 'Laos', 'Built in the 1100s by the Khmer Empire, Angkor Wat is the largest religious monument in the world and appears on Cambodia\'s flag.'],
  ['As of 2026, what is the world\'s tallest building?', 'Burj Khalifa', 'Shanghai Tower', 'Taipei 101', 'One World Trade Center', 'The Burj Khalifa in Dubai opened in 2010 and is about 828 m tall.'],
  ['In which city is the Golden Gate Bridge?', 'San Francisco', 'Los Angeles', 'Seattle', 'New York', 'The bridge opened in 1937. Its color is officially called "International Orange".'],
  ['In which city is the Parthenon?', 'Athens', 'Rome', 'Istanbul', 'Sparta', 'The Parthenon was built on the Acropolis in the 5th century BC as a temple to the goddess Athena.'],
  ['In which country is the Maya city of Chichén Itzá?', 'Mexico', 'Guatemala', 'Peru', 'Belize', 'Its El Castillo pyramid has 365 steps in total, one for each day of the year.'],
  ['In which Italian city is the famous leaning tower?', 'Pisa', 'Florence', 'Siena', 'Bologna', 'The tower began to lean during construction in the 1170s because of soft ground. Engineering work around 2000 reduced the tilt.'],
  ['In which city is St. Basil\'s Cathedral, with its colorful onion domes?', 'Moscow', 'Saint Petersburg', 'Kyiv', 'Minsk', 'St. Basil\'s was built on Red Square in the 1550s, under Ivan the Terrible.'],
  ['The architect of the Sydney Opera House came from which country?', 'Denmark', 'Australia', 'Sweden', 'United Kingdom', 'Jørn Utzon designed it. It opened in 1973, but Utzon had left the project years earlier and never saw it finished.'],
  ['Which prehistoric monument in England is a ring of standing stones?', 'Stonehenge', 'Hadrian\'s Wall', 'The Tower of London', 'Offa\'s Dyke', 'Stonehenge was built in stages from about 3000 BC to 2000 BC and lines up with the midsummer sunrise.'],
  ['How many US presidents are carved into Mount Rushmore?', '4', '3', '5', '6', 'Washington, Jefferson, Theodore Roosevelt and Lincoln, each face about 18 m tall.'],
  ['In which city is the Forbidden City?', 'Beijing', 'Shanghai', 'Xi\'an', 'Hong Kong', 'The Forbidden City was the palace of Chinese emperors for about 500 years, from the Ming to the Qing dynasty.'],
  ['In which country is Neuschwanstein Castle?', 'Germany', 'Austria', 'Switzerland', 'Czechia', 'King Ludwig II of Bavaria built it, and it inspired Disney\'s Sleeping Beauty Castle.'],
  ['In which Spanish city is the Alhambra palace?', 'Granada', 'Córdoba', 'Seville', 'Toledo', 'The Alhambra was built mainly by the Nasrids, the last Muslim dynasty in Spain, in the 13th and 14th centuries.'],
  ['Which museum has a glass pyramid at its entrance?', 'The Louvre', 'The British Museum', 'The Prado', 'The Rijksmuseum', 'The pyramid, designed by architect I. M. Pei, opened in 1989.'],
  ['Which city is home to the Little Mermaid statue?', 'Copenhagen', 'Oslo', 'Stockholm', 'Amsterdam', 'The statue, unveiled in 1913, honors Hans Christian Andersen\'s fairy tale.'],
  ['Where are the giant moai stone statues?', 'Easter Island', 'Hawaii', 'Tahiti', 'Galápagos Islands', 'Easter Island (Rapa Nui) belongs to Chile and has nearly 1,000 moai.'],
  ['In which country is Machu Picchu?', 'Peru', 'Bolivia', 'Chile', 'Ecuador', 'Machu Picchu was little known outside Peru until Hiram Bingham publicized it in 1911.'],
  ['In which city is the Hagia Sophia?', 'Istanbul', 'Athens', 'Cairo', 'Jerusalem', 'Built in 537 AD as a cathedral, it later became a mosque, then a museum, and has been a mosque again since 2020.'],
  ['The Atomium, shaped like a giant iron crystal, is in which city?', 'Brussels', 'Amsterdam', 'Luxembourg', 'Paris', 'Built for the 1958 World\'s Fair, it shows an iron crystal magnified 165 billion times.'],
  ['Can the Great Wall of China be seen from the Moon with the naked eye?', 'No, it\'s a myth', 'Yes, easily', 'Only at night', 'Only during a full Moon', 'The wall is very long but only a few meters wide, far too narrow to see from the Moon. It\'s hard to spot even from low orbit.'],
  ['In which city is the golden Shwedagon Pagoda?', 'Yangon', 'Bangkok', 'Mandalay', 'Phnom Penh', 'The Shwedagon is Myanmar\'s most sacred Buddhist site, covered in gold and topped with diamonds.'],
  ['Which of the Seven Wonders of the Ancient World is still standing?', 'The Great Pyramid of Giza', 'The Colossus of Rhodes', 'The Lighthouse of Alexandria', 'The Temple of Artemis', 'The Great Pyramid is the oldest of the seven wonders, and the only one that survives.'],
  ['In which city is the Hermitage Museum?', 'Saint Petersburg', 'Moscow', 'Vienna', 'Warsaw', 'Its main building is the Winter Palace, former home of the Russian tsars.'],
  ['In which country are the ruins of Persepolis?', 'Iran', 'Iraq', 'Turkey', 'Egypt', 'Persepolis was a capital of the Persian Empire, founded by Darius I around 518 BC and burned by Alexander the Great.'],
  ['Who designed the Guggenheim Museum in Bilbao?', 'Frank Gehry', 'Zaha Hadid', 'Norman Foster', 'Renzo Piano', 'Opened in 1997, its curving titanium shell transformed Bilbao into a tourist destination, the so-called "Bilbao effect".'],
  ['In which Indian city is the Golden Temple?', 'Amritsar', 'Delhi', 'Jaipur', 'Varanasi', 'The Golden Temple is the holiest site of Sikhism, and its free kitchen serves meals to tens of thousands of people every day.'],
  ['Which city\'s cathedral has the famous dome designed by Filippo Brunelleschi?', 'Florence', 'Rome', 'Milan', 'Venice', 'Finished in 1436, it\'s still the largest brick dome ever built.'],
  ['Which ancient Roman building has the world\'s largest unreinforced concrete dome?', 'The Pantheon', 'The Colosseum', 'The Baths of Caracalla', 'Hadrian\'s Villa', 'The Pantheon\'s dome, built around 125 AD, has an open hole at the top called the oculus.'],
  ['In which city is the Space Needle?', 'Seattle', 'Toronto', 'San Francisco', 'Chicago', 'The Space Needle was built for the 1962 World\'s Fair.'],
  ['In which country are the Meteora monasteries, perched on top of huge rock pillars?', 'Greece', 'Turkey', 'Bulgaria', 'Italy', 'Monks began building there in the 14th century. Supplies (and visitors) were once hauled up in nets.'],
  ['In which city is the Potala Palace?', 'Lhasa', 'Kathmandu', 'Thimphu', 'Beijing', 'The Potala Palace in Tibet was the winter home of the Dalai Lamas.'],
  ['In which city is the sail-shaped Burj Al Arab hotel?', 'Dubai', 'Abu Dhabi', 'Doha', 'Riyadh', 'It stands on an artificial island and was designed to look like the sail of a ship.'],
  ['In which country are the ruins of the ancient city of Ephesus?', 'Turkey', 'Greece', 'Italy', 'Egypt', 'Its Temple of Artemis was one of the Seven Wonders of the Ancient World.'],
  ['In which city is the Charles Bridge?', 'Prague', 'Budapest', 'Vienna', 'Kraków', 'Construction began in 1357 under Emperor Charles IV. The bridge is lined with 30 statues.'],
  ['In which city is St. Mark\'s Basilica?', 'Venice', 'Rome', 'Florence', 'Milan', 'It was built to hold the relics of Saint Mark, which Venetian merchants smuggled out of Alexandria in 828.'],
  ['In which US city is the Gateway Arch?', 'St. Louis', 'Chicago', 'Denver', 'Kansas City', 'At 192 m, it\'s the tallest arch in the world. It celebrates the westward expansion of the United States.'],
  ['In which country is the tidal island abbey of Mont-Saint-Michel?', 'France', 'Belgium', 'England', 'Ireland', 'It has a similar-looking cousin across the Channel in Cornwall: St Michael\'s Mount.'],
  ['In which city are the Petronas Twin Towers?', 'Kuala Lumpur', 'Singapore', 'Jakarta', 'Bangkok', 'From 1998 to 2004 they were the tallest buildings in the world.'],
  ['Which London bridge has two towers and a road that lifts to let ships pass?', 'Tower Bridge', 'London Bridge', 'Westminster Bridge', 'Millennium Bridge', 'It opened in 1894. It\'s often mistaken for London Bridge, a plain bridge nearby.'],
  ['In which country is the Terracotta Army?', 'China', 'Japan', 'South Korea', 'Mongolia', 'Farmers digging a well found it in 1974. Thousands of clay soldiers guard the tomb of Qin Shi Huang, China\'s first emperor.'],
  ['In which city is the CN Tower?', 'Toronto', 'Vancouver', 'Montreal', 'Ottawa', 'At 553 m, it was the world\'s tallest free-standing structure for over 30 years, until the Burj Khalifa passed it.'],
  ['Which city lies at the foot of Table Mountain?', 'Cape Town', 'Johannesburg', 'Durban', 'Nairobi', 'Its flat top is often covered by a layer of cloud nicknamed "the tablecloth".'],
];
