export default [
  ['Which band released the album "Abbey Road"?', 'The Beatles', 'The Rolling Stones', 'Pink Floyd', 'The Who', '"Abbey Road" (1969) is named after the London street where the Beatles recorded. Its zebra-crossing cover is world-famous.'],
  ['Who is known as the "King of Pop"?', 'Michael Jackson', 'Elvis Presley', 'Prince', 'Justin Timberlake', 'Michael Jackson\'s "Thriller" (1982) is widely reported to be the best-selling album of all time.'],
  ['How many keys does a standard piano have?', '88', '76', '92', '64', 'A standard piano has 52 white keys and 36 black keys.'],
  ['Who composed the "Moonlight Sonata"?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Frédéric Chopin', 'Beethoven titled it "Sonata quasi una fantasia" (today\'s Piano Sonata No. 14). The nickname "Moonlight" came from a critic after his death.'],
  ['Freddie Mercury was the lead singer of which band?', 'Queen', 'Led Zeppelin', 'Aerosmith', 'The Police', 'Freddie Mercury, born Farrokh Bulsara in Zanzibar, wrote "Bohemian Rhapsody".'],
  ['How many strings does a standard guitar have?', '6', '4', '5', '7', 'Standard tuning, from the lowest string to the highest, is E A D G B E.'],
  ['Which artist released the album "1989"?', 'Taylor Swift', 'Katy Perry', 'Adele', 'Lady Gaga', 'The album is named after Taylor Swift\'s birth year and won the Grammy for Album of the Year.'],
  ['Which country is ABBA from?', 'Sweden', 'Norway', 'Denmark', 'Finland', 'ABBA won the Eurovision Song Contest in 1974 with "Waterloo".'],
  ['Who is known as the "King of Rock and Roll"?', 'Elvis Presley', 'Chuck Berry', 'Little Richard', 'Buddy Holly', 'Elvis\'s home, Graceland in Memphis, is now a museum visited by around 600,000 people a year.'],
  ['Which instrument is Jimi Hendrix famous for?', 'Electric guitar', 'Drums', 'Bass guitar', 'Saxophone', 'Hendrix was left-handed and often played a right-handed guitar flipped upside down.'],
  ['In which city was Mozart born?', 'Salzburg', 'Vienna', 'Prague', 'Munich', 'Mozart was born in Salzburg in 1756 and was composing short pieces by the age of five.'],
  ['Who sang "Rolling in the Deep"?', 'Adele', 'Amy Winehouse', 'Duffy', 'Florence Welch', '"Rolling in the Deep" was the first single from Adele\'s album "21".'],
  ['What do you call a group of four musicians?', 'Quartet', 'Trio', 'Quintet', 'Octet', 'A classic string quartet is two violins, a viola and a cello.'],
  ['Which rapper\'s real name is Marshall Mathers?', 'Eminem', '50 Cent', 'Dr. Dre', 'Snoop Dogg', 'His stage name comes from his initials: M&M.'],
  ['Bob Marley is most associated with which genre?', 'Reggae', 'Ska', 'Calypso', 'Soul', 'Reggae developed in Jamaica in the late 1960s, and Bob Marley made it famous worldwide.'],
  ['Which band released "Smells Like Teen Spirit"?', 'Nirvana', 'Pearl Jam', 'Soundgarden', 'Foo Fighters', 'Nirvana\'s album "Nevermind" (1991) brought grunge from Seattle into the mainstream.'],
  ['Which Italian composer wrote "The Four Seasons"?', 'Antonio Vivaldi', 'Giuseppe Verdi', 'Giacomo Puccini', 'Gioachino Rossini', '"The Four Seasons" is a set of four violin concertos, each painting a season in music.'],
  ['Which musical term means "very loud"?', 'Fortissimo', 'Pianissimo', 'Allegro', 'Adagio', 'Music uses Italian terms: piano means soft, forte loud, pianissimo very soft and fortissimo very loud.'],
  ['Which K-pop group released "Dynamite" in 2020?', 'BTS', 'Blackpink', 'EXO', 'Twice', '"Dynamite" was BTS\'s first song fully in English and their first US number one.'],
  ['How many lines are there in a musical staff?', '5', '4', '6', '7', 'Notes sit on the staff\'s five lines and in the four spaces between them.'],
  ['Which French electronic duo performed wearing robot helmets?', 'Daft Punk', 'Justice', 'Air', 'Cassius', 'Daft Punk, Thomas Bangalter and Guy-Manuel de Homem-Christo, split up in 2021.'],
  ['Who is widely known as the "Queen of Pop"?', 'Madonna', 'Beyoncé', 'Britney Spears', 'Whitney Houston', 'Madonna\'s many hits include "Like a Virgin", "Material Girl" and "Vogue".'],
  ['Who wrote and recorded "Like a Rolling Stone"?', 'Bob Dylan', 'Mick Jagger', 'Bruce Springsteen', 'Neil Young', 'Bob Dylan won the 2016 Nobel Prize in Literature for his songwriting.'],
  ['What nationality was the composer Frédéric Chopin?', 'Polish', 'French', 'Austrian', 'Hungarian', 'Chopin was born near Warsaw in 1810 and later lived in Paris. His heart is kept in a church in Warsaw.'],
  ['Chris Martin is the lead singer of which band?', 'Coldplay', 'Keane', 'Radiohead', 'Muse', 'Coldplay\'s members met as students at University College London in the late 1990s.'],
  ['Which instrument is Yo-Yo Ma famous for playing?', 'Cello', 'Violin', 'Piano', 'Double bass', 'Yo-Yo Ma was born in Paris to Chinese parents and has won more than 15 Grammy Awards.'],
  ['How many symphonies did Beethoven complete?', '9', '5', '7', '12', 'His Ninth Symphony includes the "Ode to Joy", now the anthem of the European Union.'],
  ['Which singer\'s real name is Stefani Germanotta?', 'Lady Gaga', 'Gwen Stefani', 'Madonna', 'Katy Perry', 'Lady Gaga took her name from Queen\'s song "Radio Ga Ga".'],
  ['What is the highest standard female singing voice?', 'Soprano', 'Alto', 'Mezzo-soprano', 'Contralto', 'From high to low: soprano, mezzo-soprano and alto (contralto); for men, tenor, baritone and bass.'],
  ['Which band released "Hotel California"?', 'Eagles', 'Fleetwood Mac', 'The Doors', 'Lynyrd Skynyrd', '"Hotel California" (1976) won the Grammy for Record of the Year.'],
  ['The tango dance and music originated mainly in which country?', 'Argentina', 'Spain', 'Brazil', 'Cuba', 'Tango was born in the late 1800s in the working-class neighborhoods of Buenos Aires and Montevideo.'],
  ['Which Beatle was shot dead in New York in 1980?', 'John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Starr', 'Lennon was killed on 8 December 1980 outside the Dakota, his apartment building in New York.'],
  ['What is the name of Beyoncé\'s 2016 visual album?', 'Lemonade', 'Renaissance', '4', 'Dangerously in Love', '"Lemonade" came with an hour-long film and explores infidelity and Black womanhood.'],
  ['Who composed the opera "The Magic Flute"?', 'Wolfgang Amadeus Mozart', 'Joseph Haydn', 'Richard Wagner', 'George Frideric Handel', '"The Magic Flute" premiered in Vienna in 1791, about two months before Mozart died.'],
  ['Which brass instrument uses a slide to change notes?', 'Trombone', 'Trumpet', 'Tuba', 'French horn', 'Trombonists move the slide between seven positions to change the length of the tubing.'],
  ['Which country is the band U2 from?', 'Ireland', 'United Kingdom', 'United States', 'Australia', 'U2 formed in Dublin in 1976 while the members were still at school.'],
  ['Who is known as the "Queen of Soul"?', 'Aretha Franklin', 'Diana Ross', 'Tina Turner', 'Etta James', 'Her 1967 hit "Respect" became an anthem of the civil rights and women\'s movements.'],
  ['What does "a cappella" mean?', 'Singing without instruments', 'Played by a full orchestra', 'Played very fast', 'Sung very quietly', 'It\'s Italian for "in the manner of the chapel", after church choirs singing without instruments.'],
  ['Which Swedish DJ released "Wake Me Up" in 2013?', 'Avicii', 'Alesso', 'Kygo', 'Zedd', 'Avicii, born Tim Bergling in Stockholm, was also famous for the hit "Levels". Kygo is Norwegian.'],
  ['Who recorded the song and album "Purple Rain"?', 'Prince', 'Michael Jackson', 'Stevie Wonder', 'David Bowie', '"Purple Rain" (1984) was also a film starring Prince, and won an Oscar for Best Original Song Score.'],
  ['Which musician created the alter ego Ziggy Stardust?', 'David Bowie', 'Elton John', 'Freddie Mercury', 'Iggy Pop', 'Bowie introduced Ziggy, a rock star from outer space, on his 1972 album.'],
  ['Which instrument family does the clarinet belong to?', 'Woodwind', 'Brass', 'Strings', 'Percussion', 'Clarinets use a single reed. Saxophones are woodwinds too, even though they\'re made of brass.'],
  ['Whose ballet "The Rite of Spring" caused an uproar at its 1913 Paris premiere?', 'Igor Stravinsky', 'Claude Debussy', 'Maurice Ravel', 'Sergei Rachmaninoff', 'Its wild rhythms and dancing shocked the audience, which started shouting and booing during the performance.'],
  ['What is the time signature of a waltz?', '3/4', '4/4', '2/4', '6/8', 'Three beats to a bar gives the waltz its "ONE-two-three" swing.'],
  ['Which Beatles album ends with "A Day in the Life"?', 'Sgt. Pepper\'s Lonely Hearts Club Band', 'Revolver', 'Abbey Road', 'Help!', 'Released in 1967, it ends with a huge orchestral crescendo and a piano chord that rings for over 40 seconds.'],
  ['Which jazz trumpeter and singer recorded "What a Wonderful World"?', 'Louis Armstrong', 'Miles Davis', 'Dizzy Gillespie', 'Chet Baker', 'Armstrong, nicknamed "Satchmo", recorded it in 1967.'],
  ['How many semitones are in an octave?', '12', '8', '7', '10', 'On a piano, that\'s 12 steps from one C to the next: 7 white keys and 5 black keys.'],
  ['Who composed the ballet "The Nutcracker"?', 'Pyotr Ilyich Tchaikovsky', 'Sergei Prokofiev', 'Igor Stravinsky', 'Johann Strauss II', 'Tchaikovsky also wrote "Swan Lake" and "The Sleeping Beauty".'],
  ['Which band released "The Dark Side of the Moon"?', 'Pink Floyd', 'Led Zeppelin', 'Genesis', 'The Who', 'The 1973 album spent more than 900 weeks on the US Billboard 200 chart.'],
  ['Which musical term means "gradually getting louder"?', 'Crescendo', 'Diminuendo', 'Staccato', 'Legato', 'Diminuendo means gradually softer. Staccato means short, detached notes; legato means smooth and connected.'],
  ['Who composed the piano piece "Für Elise"?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Franz Schubert', 'Frédéric Chopin', 'It was only published after Beethoven\'s death, and nobody knows for sure who "Elise" was.'],
  ['Which French singer was nicknamed "the Little Sparrow"?', 'Édith Piaf', 'Dalida', 'Juliette Gréco', 'Barbara', '"Piaf" is French slang for sparrow. Her classics include "La Vie en rose" and "Non, je ne regrette rien".'],
  ['Which instrument did jazz legend Miles Davis play?', 'Trumpet', 'Saxophone', 'Piano', 'Double bass', 'His 1959 album "Kind of Blue" is often called the best-selling jazz album of all time.'],
  ['Who composed "The Blue Danube" waltz?', 'Johann Strauss II', 'Richard Strauss', 'Franz Schubert', 'Joseph Haydn', 'Strauss II was nicknamed "the Waltz King". Richard Strauss was a later German composer, not related to him.'],
  ['How many strings does a standard violin have?', '4', '5', '6', '3', 'They are tuned G, D, A and E, each a fifth apart.'],
  ['Which rock singer is nicknamed "The Boss"?', 'Bruce Springsteen', 'Jon Bon Jovi', 'Tom Petty', 'Billy Joel', 'He reportedly got the nickname early on because he collected the band\'s pay and shared it out.'],
  ['Which band had hits with "Wonderwall" and "Don\'t Look Back in Anger"?', 'Oasis', 'Blur', 'Radiohead', 'The Verve', 'The band was led by brothers Liam and Noel Gallagher, famous for their feuds.'],
  ['Who composed the opera "La traviata"?', 'Giuseppe Verdi', 'Giacomo Puccini', 'Gioachino Rossini', 'Wolfgang Amadeus Mozart', 'Verdi also wrote "Aida" and "Rigoletto". Puccini wrote "La bohème" and "Madama Butterfly".'],
  ['As a musical instruction, what does "piano" mean?', 'Softly', 'Loudly', 'Quickly', 'Slowly', 'The instrument\'s full name, "pianoforte", means "soft-loud", because it could play both, unlike the harpsichord.'],
  ['Which Icelandic singer released the albums "Debut" and "Homogenic"?', 'Björk', 'Enya', 'Sinéad O\'Connor', 'Robyn', 'Before going solo, she sang with the Icelandic band the Sugarcubes.'],
  ['The didgeridoo comes from which country?', 'Australia', 'New Zealand', 'Papua New Guinea', 'South Africa', 'It\'s a wind instrument of Aboriginal Australians, traditionally made from a eucalyptus trunk hollowed out by termites.'],
  ['Which Beatle was the band\'s drummer?', 'Ringo Starr', 'George Harrison', 'Paul McCartney', 'John Lennon', 'His real name is Richard Starkey. He replaced the band\'s earlier drummer, Pete Best, in 1962.'],
  ['Which orchestral instrument usually has 47 strings and seven pedals?', 'Harp', 'Piano', 'Harpsichord', 'Cello', 'The pedals shift each note up or down a semitone, letting the harp play in any key.'],
];
