export default [
  ['In Greek mythology, who is the king of the gods?', 'Zeus', 'Poseidon', 'Hades', 'Apollo', 'Zeus ruled from Mount Olympus and threw thunderbolts. Poseidon and Hades were his brothers.'],
  ['What is the Roman name for Zeus?', 'Jupiter', 'Mars', 'Neptune', 'Saturn', 'The Romans took over many Greek gods under new names. The planet Jupiter is named after him.'],
  ['What is the name of Thor\'s hammer?', 'Mjölnir', 'Gungnir', 'Excalibur', 'Gram', 'Mjölnir always comes back to Thor\'s hand after he throws it. Gungnir is Odin\'s spear.'],
  ['Who is the Greek god of the sea?', 'Poseidon', 'Hermes', 'Ares', 'Hephaestus', 'Poseidon carries a trident and was also god of earthquakes and horses. The Romans called him Neptune.'],
  ['Which Greek hero had to complete twelve labors?', 'Heracles', 'Perseus', 'Theseus', 'Achilles', 'Heracles is the Greek name. Hercules is the Roman version.'],
  ['Which hero beheaded Medusa?', 'Perseus', 'Theseus', 'Jason', 'Odysseus', 'Perseus used a polished shield as a mirror so he never had to look at her directly.'],
  ['Which Egyptian god is shown with the head of a jackal?', 'Anubis', 'Ra', 'Horus', 'Osiris', 'Anubis was the god of mummification who guided the souls of the dead.'],
  ['Where was Achilles\' only weak spot?', 'His heel', 'His neck', 'His back', 'His eyes', 'His mother dipped him in the River Styx holding him by the heel. That\'s where "Achilles\' heel" comes from.'],
  ['Who is the Norse trickster god?', 'Loki', 'Thor', 'Odin', 'Baldur', 'Loki is a shape-shifter. In one myth he becomes a mare and gives birth to Odin\'s horse, Sleipnir.'],
  ['Which creature is half man, half bull?', 'Minotaur', 'Centaur', 'Satyr', 'Sphinx', 'The Minotaur lived in the Labyrinth on Crete until the hero Theseus killed it. A centaur is half man, half horse.'],
  ['Which Titan was condemned to hold up the sky?', 'Atlas', 'Prometheus', 'Cronus', 'Hyperion', 'Atlas fought against the Olympian gods. The Atlas Mountains, and books of maps, are named after him.'],
  ['Who stole fire from the gods and gave it to humans?', 'Prometheus', 'Epimetheus', 'Atlas', 'Hermes', 'As punishment, Zeus chained Prometheus to a rock where an eagle ate his liver every day.'],
  ['Who rules the underworld in Greek mythology?', 'Hades', 'Thanatos', 'Ares', 'Cronus', '"Hades" is the name of both the god and his realm. The Romans called him Pluto.'],
  ['Who is the Greek goddess of wisdom?', 'Athena', 'Aphrodite', 'Hera', 'Artemis', 'Athena was the patron goddess of Athens, and the Parthenon was her temple.'],
  ['Who is the Roman goddess of love?', 'Venus', 'Juno', 'Minerva', 'Diana', 'Venus is the Roman version of the Greek Aphrodite. The planet Venus is named after her.'],
  ['In Norse mythology, where do warriors who die in battle go to feast with Odin?', 'Valhalla', 'Asgard', 'Midgard', 'Helheim', 'Valhalla is a great hall in Asgard, and the Valkyries choose which fallen warriors go there.'],
  ['Who opened a jar (often called a box) that released evils into the world?', 'Pandora', 'Persephone', 'Helen', 'Medea', 'When Pandora closed the jar again, only hope was left inside.'],
  ['Everything King Midas touched turned into what?', 'Gold', 'Stone', 'Silver', 'Ice', 'Even his food turned to gold, so his wish quickly became a curse.'],
  ['Who flew too close to the Sun on wings of feathers and wax?', 'Icarus', 'Daedalus', 'Phaethon', 'Bellerophon', 'His father Daedalus made the wings. The Sun melted the wax and Icarus fell into the sea.'],
  ['Which winged horse sprang from Medusa when she was beheaded?', 'Pegasus', 'Sleipnir', 'Arion', 'Chiron', 'The hero Bellerophon later rode Pegasus to fight the fire-breathing Chimera.'],
  ['How many legs does Odin\'s horse Sleipnir have?', '8', '4', '6', '12', 'Sleipnir is the fastest of all horses and can ride through the sky and into the underworld.'],
  ['Who is the Egyptian sun god?', 'Ra', 'Anubis', 'Set', 'Thoth', 'Ra was often shown with a falcon\'s head topped by a sun disk.'],
  ['Which Greek god is the winged messenger of the gods?', 'Hermes', 'Apollo', 'Dionysus', 'Ares', 'Hermes wore winged sandals and also guided souls to the underworld. The Romans called him Mercury.'],
  ['What is the giant tree that connects the nine worlds in Norse mythology?', 'Yggdrasil', 'Bifröst', 'Valhalla', 'Asgard', 'Yggdrasil is a giant ash tree. Bifröst is the rainbow bridge leading to Asgard.'],
  ['Who is the wife of Zeus and queen of the gods?', 'Hera', 'Athena', 'Demeter', 'Aphrodite', 'Hera was the goddess of marriage and family. The Romans called her Juno.'],
  ['Which monster had snakes for hair and could turn people to stone?', 'Medusa', 'Hydra', 'Scylla', 'Chimera', 'Medusa was one of three Gorgon sisters, and the only one who was mortal.'],
  ['Which Greek hero came up with the Trojan Horse?', 'Odysseus', 'Achilles', 'Agamemnon', 'Hector', 'Greek soldiers hid inside the wooden horse, and the Trojans pulled it into their own city.'],
  ['Which twins are said to have founded Rome?', 'Romulus and Remus', 'Castor and Pollux', 'Apollo and Artemis', 'Cain and Abel', 'Legend says a she-wolf raised the twins, and Romulus founded Rome in 753 BC.'],
  ['Who is the Greek god of wine?', 'Dionysus', 'Apollo', 'Hermes', 'Pan', 'Dionysus was also the god of festivals and theater. The Romans called him Bacchus.'],
  ['Who is the Greek goddess of the harvest and agriculture?', 'Demeter', 'Hestia', 'Persephone', 'Gaia', 'Greeks explained winter as Demeter\'s grief while her daughter Persephone spent part of the year in the underworld.'],
  ['In Norse mythology, what is the final battle at the end of the world called?', 'Ragnarök', 'Valhalla', 'Midgard', 'Fimbulwinter', 'At Ragnarök, Thor and Odin die fighting giants and monsters. Fimbulwinter is the great winter that comes before it.'],
  ['Who is the Greek god of fire and blacksmiths?', 'Hephaestus', 'Ares', 'Hermes', 'Apollo', 'Hephaestus forged weapons and armor for gods and heroes, including the armor of Achilles. The Romans called him Vulcan.'],
  ['What is the name of the three-headed dog that guards the Greek underworld?', 'Cerberus', 'Orthrus', 'Typhon', 'Fenrir', 'Capturing Cerberus was the last of Heracles\'s twelve labors. Fenrir is a giant wolf from Norse myth.'],
  ['Which Egyptian god was killed by his brother Set and became ruler of the afterlife?', 'Osiris', 'Ra', 'Anubis', 'Thoth', 'His wife Isis brought him back to life, and their son Horus later avenged him.'],
  ['Who is Odin\'s wife in Norse mythology?', 'Frigg', 'Freyja', 'Sif', 'Hel', 'Frigg could see the future but never revealed it. Sif is Thor\'s wife, and Friday may be named after Frigg.'],
  ['What helped Theseus find his way out of the Labyrinth?', 'A ball of thread', 'A trail of breadcrumbs', 'A magic lamp', 'A map drawn on his shield', 'Princess Ariadne gave him the thread, which he unrolled on the way in and followed back out.'],
  ['Who was the sea-nymph mother of Achilles?', 'Thetis', 'Hera', 'Athena', 'Penelope', 'Thetis dipped baby Achilles in the River Styx to make him invulnerable, except for the heel she held.'],
  ['Which Hindu god has the head of an elephant?', 'Ganesha', 'Hanuman', 'Vishnu', 'Shiva', 'Ganesha is the remover of obstacles and the god of new beginnings. Hanuman is the monkey god.'],
  ['What was the name of Jason\'s ship in the quest for the Golden Fleece?', 'Argo', 'Pegasus', 'Olympia', 'Trireme', 'Its crew, the Argonauts, were named after the ship and included Heracles and Orpheus.'],
  ['Who solved the riddle of the Sphinx?', 'Oedipus', 'Odysseus', 'Perseus', 'Theseus', 'The riddle: what walks on four legs in the morning, two at noon and three in the evening? A human, crawling, walking, then with a cane.'],
  ['Which Aztec god is a feathered serpent?', 'Quetzalcoatl', 'Huitzilopochtli', 'Tlaloc', 'Xipe Totec', 'The Maya worshipped a similar feathered serpent called Kukulkan. Tlaloc was the Aztec rain god.'],
];
