export default [
  ['What is the largest mammal in the world?', 'Blue whale', 'African elephant', 'Sperm whale', 'Whale shark', 'Blue whales can reach about 30 m long, making them the largest animals known to have ever lived.'],
  ['How many legs does a spider have?', '8', '6', '10', '12', 'Spiders are arachnids, not insects. Insects have six legs.'],
  ['What is the fastest land animal?', 'Cheetah', 'Lion', 'Pronghorn', 'Greyhound', 'Cheetahs can reach around 100 km/h, but only in short sprints of a few hundred meters.'],
  ['What is a baby kangaroo called?', 'Joey', 'Cub', 'Kid', 'Pup', 'A joey is born about the size of a jellybean and finishes growing in its mother\'s pouch.'],
  ['Which bird can fly backwards?', 'Hummingbird', 'Swift', 'Kingfisher', 'Sparrow', 'Hummingbirds beat their wings in a figure-eight pattern, which lets them hover and even fly backwards.'],
  ['What is a group of lions called?', 'Pride', 'Pack', 'Herd', 'Flock', 'Lions are the only truly social big cats. A pride is mostly related females, their cubs and a few males.'],
  ['How many hearts does an octopus have?', '3', '1', '2', '8', 'Two hearts pump blood through the gills and one through the body. Octopus blood is blue because it\'s copper-based.'],
  ['Which is the tallest animal?', 'Giraffe', 'Elephant', 'Ostrich', 'Moose', 'Giraffes can be over 5 m tall, yet their neck has just seven vertebrae, the same number as ours.'],
  ['Which is the only mammal capable of true flight?', 'Bat', 'Flying squirrel', 'Sugar glider', 'Colugo', 'Bats make up about a fifth of all mammal species. Flying squirrels and sugar gliders can only glide.'],
  ['What do giant pandas mainly eat?', 'Bamboo', 'Eucalyptus', 'Fish', 'Berries', 'Bamboo makes up about 99% of a panda\'s diet, and a panda can eat over 10 kg of it a day.'],
  ['What is the largest species of shark?', 'Whale shark', 'Great white shark', 'Basking shark', 'Tiger shark', 'Whale sharks can grow to around 18 m, but they are gentle filter feeders that eat plankton.'],
  ['Which tree produces acorns?', 'Oak', 'Maple', 'Birch', 'Pine', 'An acorn is a nut holding a single seed. A big oak can drop thousands of them in a good year.'],
  ['How many compartments does a cow\'s stomach have?', '4', '2', '3', '6', 'The four parts are the rumen, reticulum, omasum and abomasum. Cows chew their cud to break down tough grass.'],
  ['What is the largest living bird?', 'Ostrich', 'Emu', 'Albatross', 'Condor', 'Ostriches can\'t fly, but they can run at about 70 km/h and lay the largest eggs of any living bird.'],
  ['Koalas are native to which country?', 'Australia', 'New Zealand', 'Indonesia', 'South Africa', 'Koalas are marsupials, not bears, and live wild only in eastern and southern Australia.'],
  ['What is the largest species of wild cat?', 'Tiger', 'Lion', 'Jaguar', 'Leopard', 'Big male tigers can weigh around 300 kg, and every tiger\'s stripe pattern is unique.'],
  ['What is a male bee called?', 'Drone', 'Worker', 'Soldier', 'Buck', 'Drones have no sting and don\'t collect food. Their main job is to mate with a queen.'],
  ['What is the largest rainforest in the world?', 'Amazon', 'Congo', 'Daintree', 'Borneo', 'The Amazon rainforest covers about 5.5 million km² across nine countries, most of it in Brazil.'],
  ['How many legs does an insect have?', '6', '8', '4', '10', 'Insects have six legs and three body parts: head, thorax and abdomen.'],
  ['Which ape is one of humans\' closest living relatives?', 'Chimpanzee', 'Gorilla', 'Orangutan', 'Gibbon', 'Chimpanzees and bonobos share about 98–99% of their DNA with humans.'],
  ['What is the process of a caterpillar turning into a butterfly called?', 'Metamorphosis', 'Photosynthesis', 'Mitosis', 'Hibernation', 'Inside the chrysalis, much of the caterpillar\'s body breaks down and is rebuilt as a butterfly.'],
  ['Which mammal is famous for being extremely slow-moving?', 'Sloth', 'Koala', 'Panda', 'Hedgehog', 'Sloths move so slowly that algae grows in their fur, which helps camouflage them.'],
  ['What kind of animal is a Komodo dragon?', 'Lizard', 'Snake', 'Crocodile', 'Salamander', 'It\'s the largest living lizard, up to about 3 m long, found only on a few Indonesian islands.'],
  ['Which flower is famously associated with the Netherlands?', 'Tulip', 'Rose', 'Daisy', 'Sunflower', 'Tulips originally came from Central Asia and reached the Netherlands via the Ottoman Empire in the late 1500s.'],
  ['What is a group of crows called?', 'A murder', 'A parliament', 'A gaggle', 'A pod', 'Other odd group names: a parliament of owls, a gaggle of geese and a pod of dolphins.'],
  ['What kind of animals are dolphins?', 'Mammals', 'Fish', 'Amphibians', 'Reptiles', 'Dolphins breathe air through a blowhole, are warm-blooded and feed their young with milk.'],
  ['Which mammal is thought to live the longest, possibly over 200 years?', 'Bowhead whale', 'African elephant', 'Blue whale', 'Orca', 'Scientists estimated one bowhead whale was over 200 years old, using chemical changes in the lenses of its eyes.'],
  ['What is a baby swan called?', 'Cygnet', 'Gosling', 'Duckling', 'Fledgling', 'A gosling is a baby goose and a duckling a baby duck.'],
  ['Which reptile is famous for changing color and moving its eyes independently?', 'Chameleon', 'Gecko', 'Iguana', 'Skink', 'Chameleons change color mostly to communicate and control their temperature, not just for camouflage.'],
  ['How many arms does a typical starfish have?', '5', '4', '6', '8', 'Most sea stars have five arms and can regrow lost ones. Despite the name, they aren\'t fish.'],
  ['What sugary liquid do bees collect from flowers to make honey?', 'Nectar', 'Pollen', 'Sap', 'Dew', 'Bees add enzymes to nectar and fan it with their wings to evaporate water, turning it into honey.'],
  ['What is the largest species of penguin?', 'Emperor penguin', 'King penguin', 'Adélie penguin', 'Gentoo penguin', 'Emperor penguins stand over a meter tall and raise their chicks through the Antarctic winter.'],
  ['What is the national animal of Scotland?', 'The unicorn', 'The lion', 'The red deer', 'The golden eagle', 'The unicorn has been a symbol of Scotland since medieval times, standing for purity and power.'],
  ['Which gas do plants release during photosynthesis?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Methane', 'Plants also use some oxygen themselves, but in daylight they release far more than they take in.'],
  ['What is a group of wolves called?', 'A pack', 'A pride', 'A herd', 'A school', 'A wolf pack is usually a family: a breeding pair and their offspring.'],
  ['Which marsupial from Tasmania is known for its loud screeching?', 'Tasmanian devil', 'Wombat', 'Quokka', 'Possum', 'Tasmanian devils are the largest surviving meat-eating marsupials and live wild only in Tasmania.'],
  ['What do koalas eat almost exclusively?', 'Eucalyptus leaves', 'Bamboo', 'Grass', 'Insects', 'Eucalyptus is low in nutrients and toxic to most animals, so koalas sleep up to 18–22 hours a day to save energy.'],
  ['Which part of a plant absorbs water from the soil?', 'Roots', 'Leaves', 'Stem', 'Flowers', 'Water travels up from the roots through tiny tubes called xylem and evaporates from the leaves.'],
  ['How many legs does a lobster have, counting its claws?', '10', '8', '6', '12', 'Lobsters are decapods, meaning "ten feet": four pairs of walking legs plus two big claws.'],
  ['Which tree species is the tallest in the world?', 'Coast redwood', 'Giant sequoia', 'Douglas fir', 'Mountain ash', 'The tallest known tree, a coast redwood called Hyperion, is about 116 m tall. Giant sequoias are the biggest by volume.'],
  ['Which big cat with a spotted coat is the largest cat native to the Americas?', 'Jaguar', 'Leopard', 'Cheetah', 'Lynx', 'Jaguars have an extremely powerful bite and, unlike most cats, are strong swimmers.'],
];
