export default [
  ['What is the chemical symbol for gold?', 'Au', 'Ag', 'Go', 'Gd', 'Au comes from "aurum", the Latin word for gold. Ag (silver) comes from "argentum".'],
  ['Which gas do plants absorb from the air for photosynthesis?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen', 'Plants use sunlight to turn carbon dioxide and water into sugar, releasing oxygen as a by-product.'],
  ['What is the hardest natural substance?', 'Diamond', 'Quartz', 'Granite', 'Titanium', 'Diamond is pure carbon, the same element as pencil graphite, locked in a very strong crystal structure.'],
  ['At sea level, at what temperature does water boil?', '100 °C', '90 °C', '110 °C', '120 °C', 'The boiling point drops as air pressure falls. On top of Mount Everest, water boils at only about 70 °C.'],
  ['What is the most abundant gas in Earth\'s atmosphere?', 'Nitrogen', 'Oxygen', 'Carbon dioxide', 'Argon', 'Air is about 78% nitrogen and 21% oxygen. Everything else makes up about 1%.'],
  ['What is the chemical symbol for sodium?', 'Na', 'So', 'Sd', 'S', 'Na comes from "natrium", the Latin name for sodium. S is sulfur.'],
  ['Who developed the theory of general relativity?', 'Albert Einstein', 'Isaac Newton', 'Niels Bohr', 'Stephen Hawking', 'Einstein published it in 1915. It describes gravity as mass curving space and time.'],
  ['Roughly how fast does light travel?', '300,000 km/s', '30,000 km/s', '3,000,000 km/s', '150,000 km/s', 'Light covers about 299,792 km every second, fast enough to circle the Earth about 7.5 times.'],
  ['Which particle in an atom has a negative charge?', 'Electron', 'Proton', 'Neutron', 'Photon', 'Electrons are negative, protons are positive and neutrons have no charge.'],
  ['What is the pH of pure water at 25 °C?', '7', '0', '5', '10', 'pH 7 is neutral. Lower values are acidic, higher values are alkaline (basic).'],
  ['Which element has the atomic number 1?', 'Hydrogen', 'Helium', 'Oxygen', 'Carbon', 'The atomic number is the number of protons. Hydrogen, the lightest element, has just one.'],
  ['What is the unit of electrical resistance?', 'Ohm', 'Volt', 'Ampere', 'Watt', 'It\'s named after German physicist Georg Ohm. Ohm\'s law: voltage = current × resistance.'],
  ['Which force keeps the planets in orbit around the Sun?', 'Gravity', 'Magnetism', 'Friction', 'Electrostatic force', 'Newton showed that the same gravity that makes an apple fall keeps the Moon and planets in orbit.'],
  ['Who proposed the theory of evolution by natural selection in "On the Origin of Species"?', 'Charles Darwin', 'Gregor Mendel', 'Jean-Baptiste Lamarck', 'Louis Pasteur', 'Darwin published the book in 1859. Alfred Russel Wallace reached the same idea independently.'],
  ['What is the freezing point of water in Fahrenheit?', '32 °F', '0 °F', '12 °F', '40 °F', 'Water freezes at 32 °F (0 °C) and boils at 212 °F (100 °C).'],
  ['Which metal is liquid at room temperature?', 'Mercury', 'Lead', 'Aluminium', 'Tin', 'Mercury stays liquid down to about −39 °C, which is why it was used in thermometers.'],
  ['What is the most common element in the universe?', 'Hydrogen', 'Helium', 'Oxygen', 'Carbon', 'About three-quarters of the ordinary matter in the universe is hydrogen, mostly inside stars.'],
  ['What does DNA stand for?', 'Deoxyribonucleic acid', 'Dinitrogen acid', 'Deoxyribose nitric acid', 'Diribonucleic acid', 'Its double-helix shape was described in 1953 by Watson and Crick, using X-ray images made by Rosalind Franklin\'s team.'],
  ['Through which of these does sound travel fastest?', 'Steel', 'Air', 'Water', 'Vacuum', 'Sound moves at about 343 m/s in air, about 1,480 m/s in water and around 5,000–6,000 m/s in steel. It can\'t travel through a vacuum at all.'],
  ['What is the chemical formula of table salt?', 'NaCl', 'KCl', 'NaOH', 'CaCl₂', 'Table salt is sodium chloride: one sodium atom for every chlorine atom.'],
  ['Who formulated the three laws of motion?', 'Isaac Newton', 'Galileo Galilei', 'Johannes Kepler', 'Albert Einstein', 'Newton published his laws of motion in his book "Principia" in 1687.'],
  ['What kind of energy does a moving object have?', 'Kinetic energy', 'Potential energy', 'Thermal energy', 'Chemical energy', 'Kinetic energy is the energy of motion. Potential energy is stored, like a ball held up high.'],
  ['What is the center of an atom called?', 'Nucleus', 'Core', 'Proton', 'Orbit', 'The nucleus holds almost all of an atom\'s mass, yet it is tens of thousands of times smaller than the atom itself.'],
  ['What is absolute zero in Celsius?', '−273.15 °C', '−100 °C', '−459.67 °C', '0 °C', 'Absolute zero (0 kelvin) is the coldest possible temperature. −459.67 is the same point in Fahrenheit.'],
  ['Which vitamin does your skin produce when exposed to sunlight?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B12', 'UVB rays let the skin make vitamin D, which the body needs to absorb calcium for strong bones.'],
  ['Which is the lightest noble gas?', 'Helium', 'Neon', 'Argon', 'Krypton', 'Helium is the second-lightest element after hydrogen, which is why helium balloons float.'],
  ['What is the chemical symbol for iron?', 'Fe', 'Ir', 'In', 'I', 'Fe comes from "ferrum", the Latin word for iron. Ir is iridium and I is iodine.'],
  ['Which part of the cell is known as its "powerhouse"?', 'Mitochondria', 'Nucleus', 'Ribosome', 'Golgi apparatus', 'Mitochondria turn nutrients into usable energy (ATP). They even carry their own small set of DNA.'],
  ['How many elements are in the periodic table today?', '118', '108', '112', '126', 'The four newest elements, up to oganesson (number 118), were officially named in 2016.'],
  ['What is the chemical symbol for potassium?', 'K', 'P', 'Po', 'Pt', 'K comes from "kalium", the Latin name for potassium. P is phosphorus and Pt is platinum.'],
  ['What kind of chemical bond is formed when atoms share pairs of electrons?', 'Covalent bond', 'Ionic bond', 'Metallic bond', 'Hydrogen bond', 'In covalent bonds, as in water, atoms share electrons. In ionic bonds, as in salt, electrons are transferred.'],
  ['What is the SI unit of force?', 'Newton', 'Joule', 'Pascal', 'Watt', 'One newton is roughly the weight of a small apple on Earth.'],
  ['What is the SI unit of energy?', 'Joule', 'Watt', 'Newton', 'Volt', 'A joule is a small amount of energy: one food Calorie (kilocalorie) is about 4,184 joules.'],
  ['Who discovered penicillin in 1928?', 'Alexander Fleming', 'Louis Pasteur', 'Joseph Lister', 'Robert Koch', 'Fleming noticed mold killing bacteria in a dish. Penicillin became the first widely used antibiotic in the 1940s.'],
  ['What is the most abundant element in Earth\'s crust?', 'Oxygen', 'Silicon', 'Iron', 'Aluminium', 'Oxygen makes up about 46% of the crust by mass, mostly locked inside rocks and minerals.'],
  ['Who published the first widely recognized periodic table in 1869?', 'Dmitri Mendeleev', 'Antoine Lavoisier', 'John Dalton', 'Niels Bohr', 'Mendeleev left gaps for elements nobody had found yet, and correctly predicted their properties.'],
  ['What is the study of fungi called?', 'Mycology', 'Botany', 'Entomology', 'Virology', 'Fungi, like mushrooms and yeast, form their own kingdom of life, more closely related to animals than to plants.'],
  ['What does a Geiger counter detect?', 'Radiation', 'Earthquakes', 'Humidity', 'Air pressure', 'It clicks each time ionizing radiation passes through its gas-filled tube.'],
  ['A solution with a pH of 3 is…', 'Acidic', 'Neutral', 'Alkaline', 'Pure water', 'Below 7 is acidic. Vinegar and lemon juice are around pH 2–3, and each step on the scale is a tenfold change.'],
  ['What is the chemical formula of ozone?', 'O₃', 'O₂', 'CO', 'H₂O₂', 'Ozone high in the stratosphere shields us from UV light, but at ground level it\'s a pollutant.'],
  ['Which color of visible light has the longest wavelength?', 'Red', 'Violet', 'Blue', 'Green', 'Red light is around 700 nanometers and violet around 400 nm, at the two ends of the rainbow.'],
  ['What are animals that eat both plants and meat called?', 'Omnivores', 'Herbivores', 'Carnivores', 'Insectivores', 'Humans, bears, pigs and raccoons are all omnivores.'],
  ['Which is the most electronegative element?', 'Fluorine', 'Oxygen', 'Chlorine', 'Nitrogen', 'Fluorine pulls on electrons so strongly that it reacts with almost every other element.'],
  ['Roughly what is Avogadro\'s number?', '6.022 × 10²³', '3.14 × 10¹⁰', '9.81 × 10²', '1.6 × 10⁻¹⁹', 'It\'s the number of particles in one mole of a substance. 1.6 × 10⁻¹⁹ is the charge of an electron in coulombs.'],
  ['Whose 1543 book argued that the Earth orbits the Sun?', 'Nicolaus Copernicus', 'Galileo Galilei', 'Johannes Kepler', 'Ptolemy', 'Aristarchus of Samos suggested it in ancient Greece, but Copernicus\'s model started a revolution in astronomy.'],
  ['What is the "half-life" of a radioactive substance?', 'The time for half of it to decay', 'Half the time it stays dangerous', 'The age at which it is half as heavy', 'Half the time it takes to melt', 'After one half-life, half the atoms remain; after two, a quarter; and so on.'],
  ['Which particle carries the electromagnetic force?', 'Photon', 'Gluon', 'W boson', 'Graviton', 'Gluons carry the strong force and W bosons the weak force. The graviton is still hypothetical.'],
  ['Which metal has the highest melting point?', 'Tungsten', 'Iron', 'Titanium', 'Platinum', 'Tungsten melts at about 3,422 °C, which is why it was used for light-bulb filaments.'],
  ['In E = mc², what does "c" stand for?', 'The speed of light', 'The speed of sound', 'Charge', 'A constant equal to 1', 'Because the speed of light is huge, a tiny amount of mass corresponds to an enormous amount of energy.'],
  ['What is a chemical reaction that gives off heat called?', 'Exothermic', 'Endothermic', 'Catalytic', 'Isothermal', 'Burning wood is exothermic. Reactions that absorb heat, like an instant cold pack, are endothermic.'],
  ['What is the main component of natural gas?', 'Methane', 'Propane', 'Butane', 'Ethane', 'Methane is a carbon atom with four hydrogens (CH₄). It\'s also a powerful greenhouse gas.'],
  ['Who discovered the electron in 1897?', 'J. J. Thomson', 'Ernest Rutherford', 'Niels Bohr', 'James Chadwick', 'Rutherford discovered the atomic nucleus in 1911 and Chadwick the neutron in 1932.'],
  ['Which law says that, at a fixed temperature, a gas\'s pressure times its volume stays constant?', 'Boyle\'s law', 'Charles\'s law', 'Hooke\'s law', 'Ohm\'s law', 'Squeeze a gas into half the space and its pressure doubles. Charles\'s law links volume and temperature.'],
];
