export default [
  ['How many players does a soccer team have on the field?', '11', '10', '9', '12', 'Each side has 11 players on the field, including the goalkeeper.'],
  ['Which country was the first to win five FIFA World Cups?', 'Brazil', 'Germany', 'Italy', 'Argentina', 'Brazil won in 1958, 1962, 1970, 1994 and 2002.'],
  ['In tennis, what is a score of zero called?', 'Love', 'Nil', 'Zero', 'Duck', 'Tennis scoring goes love, 15, 30, 40, then game.'],
  ['How many rings are on the Olympic flag?', '5', '4', '6', '7', 'The five interlocking rings stand for the five inhabited continents joined together by the Games.'],
  ['In which sport would you perform a slam dunk?', 'Basketball', 'Volleyball', 'Handball', 'Tennis', 'In a slam dunk, a player jumps and forces the ball down through the hoop.'],
  ['How long is a marathon?', '42.195 km', '40 km', '45 km', '38.5 km', 'The odd distance comes from the 1908 London Olympics course and became the official standard in 1921.'],
  ['Which city hosted the 2016 Summer Olympics?', 'Rio de Janeiro', 'Beijing', 'London', 'Tokyo', 'Rio 2016 was the first Olympics held in South America.'],
  ['In golf, what is one stroke under par called?', 'Birdie', 'Eagle', 'Bogey', 'Albatross', 'Two under par is an eagle, three under is an albatross, and one over par is a bogey.'],
  ['How many points is a touchdown worth in American football (before the extra point)?', '6', '7', '3', '5', 'After a touchdown, a team can kick for 1 extra point or try a play from close range for 2.'],
  ['Which Grand Slam tennis tournament is played on clay?', 'French Open', 'Wimbledon', 'US Open', 'Australian Open', 'The French Open is played at Roland-Garros in Paris. Wimbledon is on grass, the US and Australian Opens on hard courts.'],
  ['Who set the men\'s 100 m world record of 9.58 seconds?', 'Usain Bolt', 'Tyson Gay', 'Yohan Blake', 'Carl Lewis', 'Usain Bolt ran 9.58 s at the 2009 World Championships in Berlin.'],
  ['In which sport is the Stanley Cup awarded?', 'Ice hockey', 'Baseball', 'Basketball', 'American football', 'First awarded in 1893, the Stanley Cup is one of the oldest trophies in North American pro sports.'],
  ['How many players does a volleyball team have on court?', '6', '5', '7', '9', 'Volleyball was invented in 1895 by William G. Morgan in Massachusetts.'],
  ['What is the maximum score in a single game of ten-pin bowling?', '300', '200', '250', '500', 'A perfect 300 game takes 12 strikes in a row.'],
  ['The Tour de France is a competition in which sport?', 'Cycling', 'Running', 'Motor racing', 'Sailing', 'First held in 1903, the Tour covers roughly 3,500 km over about three weeks.'],
  ['Where were the first modern Olympic Games held in 1896?', 'Athens', 'Paris', 'London', 'Rome', 'Organized by Pierre de Coubertin, the 1896 Games had about 240 athletes, all men.'],
  ['Which sport uses the terms "scrum" and "try"?', 'Rugby', 'Cricket', 'Hockey', 'Polo', 'In rugby union, a try (grounding the ball over the line) is worth 5 points.'],
  ['How many players does a basketball team have on court?', '5', '6', '7', '4', 'James Naismith invented basketball in 1891, using peach baskets as hoops.'],
  ['In snooker, which ball is worth the most points?', 'Black', 'Pink', 'Blue', 'Red', 'Black is worth 7, pink 6, blue 5, brown 4, green 3, yellow 2 and each red 1.'],
  ['Which martial art\'s name means "the gentle way"?', 'Judo', 'Karate', 'Taekwondo', 'Kung fu', 'Judo was founded in Japan by Kanō Jigorō in 1882 and became an Olympic sport in 1964.'],
  ['What color jersey does the overall leader of the Tour de France wear?', 'Yellow', 'Green', 'Polka dot', 'Pink', 'The yellow jersey dates from 1919. Green is for the points leader and polka dot for the best climber.'],
  ['How many holes are in a standard round of golf?', '18', '9', '12', '21', 'St Andrews in Scotland set the 18-hole standard in 1764.'],
  ['In which sport would you use a shuttlecock?', 'Badminton', 'Squash', 'Table tennis', 'Tennis', 'A shuttlecock traditionally has 16 goose feathers and can leave the racket at over 400 km/h on a smash.'],
  ['Michael Phelps is famous in which sport?', 'Swimming', 'Athletics', 'Gymnastics', 'Rowing', 'Phelps won 28 Olympic medals, 23 of them gold, more than any other athlete.'],
  ['How long is an Olympic swimming pool?', '50 m', '25 m', '100 m', '75 m', 'Olympic ("long course") pools are 50 m. Short-course pools are 25 m.'],
  ['Which country was Formula 1 legend Ayrton Senna from?', 'Brazil', 'Argentina', 'Portugal', 'Spain', 'Senna won three world titles (1988, 1990, 1991) and died at the 1994 San Marino Grand Prix.'],
  ['How many players does a rugby union team have on the field?', '15', '13', '11', '12', 'Rugby union has 15 players per side, while rugby league has 13.'],
  ['In which country did judo originate?', 'Japan', 'China', 'South Korea', 'Thailand', 'Judo focuses on throws, pins and holds rather than punches and kicks.'],
  ['What is the maximum number of sets in a men\'s Grand Slam singles match?', '5', '3', '4', '7', 'Men play best of five sets at Grand Slams, women best of three.'],
  ['Which country won the first FIFA World Cup in 1930?', 'Uruguay', 'Brazil', 'Argentina', 'Italy', 'Uruguay hosted and won the first World Cup, beating Argentina 4–2 in the final.'],
  ['How long is a standard soccer match, not counting stoppage time?', '90 minutes', '80 minutes', '100 minutes', '120 minutes', 'A match is two halves of 45 minutes, and the referee adds stoppage time for delays.'],
  ['In baseball, how many strikes make a strikeout?', '3', '2', '4', '5', 'Four "balls" (pitches outside the strike zone) let the batter walk to first base.'],
  ['Which country has won the most Summer Olympic gold medals in total?', 'United States', 'Soviet Union', 'China', 'Great Britain', 'The United States has won more than 1,000 Summer Olympic gold medals.'],
  ['In cricket, how many balls are bowled in a standard over?', '6', '5', '8', '10', 'After six legal deliveries, a different bowler takes over from the other end.'],
  ['The Formula 1 Grand Prix that runs through Monte Carlo is held in which country?', 'Monaco', 'France', 'Italy', 'Spain', 'The Monaco Grand Prix has been raced through the streets of Monte Carlo since 1929.'],
  ['How high above the floor is a regulation basketball rim?', '3.05 m (10 ft)', '2.75 m (9 ft)', '3.35 m (11 ft)', '3.65 m (12 ft)', 'The 10-foot height dates back to 1891, when Naismith nailed peach baskets to a balcony railing.'],
  ['Which boxer called himself "The Greatest" and said "float like a butterfly, sting like a bee"?', 'Muhammad Ali', 'Mike Tyson', 'Joe Frazier', 'George Foreman', 'Born Cassius Clay, Ali won Olympic gold in 1960 and was world heavyweight champion three times.'],
  ['In which sport is the Ryder Cup contested?', 'Golf', 'Tennis', 'Sailing', 'Cricket', 'The Ryder Cup is played every two years between teams from Europe and the United States.'],
  ['How many players per team are on the ice in ice hockey, including the goalie?', '6', '5', '7', '11', 'Each team has five skaters and a goalie on the ice.'],
  ['Which winter sport combines cross-country skiing and rifle shooting?', 'Biathlon', 'Triathlon', 'Pentathlon', 'Nordic combined', 'Biathlon grew out of Scandinavian military ski patrols. Nordic combined mixes skiing with ski jumping.'],
  ['How often are the Summer Olympic Games normally held?', 'Every 4 years', 'Every 2 years', 'Every 3 years', 'Every 5 years', 'Tokyo 2020 was the only Games ever postponed, held in 2021 because of COVID-19.'],
  ['In chess, which piece can only move diagonally?', 'Bishop', 'Rook', 'Knight', 'King', 'Because it only moves diagonally, a bishop stays on squares of the same color for the whole game.'],
];
