export default [
  ['What does "CPU" stand for?', 'Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Core Processing Unit', 'The CPU carries out a program\'s instructions, which is why it\'s often called the computer\'s "brain".'],
  ['Who co-founded Apple with Steve Jobs?', 'Steve Wozniak', 'Bill Gates', 'Paul Allen', 'Tim Cook', 'Apple was founded in 1976. Wozniak designed the Apple I and Apple II computers.'],
  ['What does "HTTP" stand for?', 'HyperText Transfer Protocol', 'HighText Transfer Protocol', 'Hyper Transfer Text Protocol', 'HyperText Transmission Program', 'HTTP is how browsers ask for web pages. The "S" in HTTPS means the connection is encrypted.'],
  ['In which year was the first iPhone released?', '2007', '2005', '2008', '2010', 'Steve Jobs unveiled the iPhone in January 2007, and it went on sale that June.'],
  ['Which company bought Android in 2005?', 'Google', 'Samsung', 'Microsoft', 'Nokia', 'Android Inc. was founded in 2003. Google bought it in 2005, and the first Android phone came out in 2008.'],
  ['How many bits are in a byte?', '8', '4', '16', '10', 'A bit is a single 0 or 1. Eight bits make a byte, enough to store one basic text character.'],
  ['What does "URL" stand for?', 'Uniform Resource Locator', 'Universal Reference Link', 'Uniform Remote Link', 'Unified Resource Line', 'A URL is a web address, like https://example.com.'],
  ['Who invented the World Wide Web?', 'Tim Berners-Lee', 'Vint Cerf', 'Bill Gates', 'Steve Jobs', 'Berners-Lee invented the Web at CERN in 1989. The internet it runs on already existed; Vint Cerf helped create that.'],
  ['Which 1993 browser helped make the web popular with its graphical interface?', 'Mosaic', 'Firefox', 'Chrome', 'Safari', 'Mosaic was built at the University of Illinois. Some of its creators went on to make Netscape.'],
  ['Which programming language is named after a British comedy group?', 'Python', 'Ruby', 'Perl', 'Java', 'Python is named after Monty Python\'s Flying Circus, not the snake.'],
  ['What does "RAM" stand for?', 'Random Access Memory', 'Read Access Memory', 'Rapid Action Memory', 'Run Allocation Module', 'RAM is fast, short-term working memory, and it\'s wiped when the computer turns off.'],
  ['Which company makes the PlayStation?', 'Sony', 'Nintendo', 'Microsoft', 'Sega', 'Sony released the first PlayStation in Japan in 1994.'],
  ['What does Wi-Fi use to transmit data?', 'Radio waves', 'Infrared light', 'Sound waves', 'Visible light', 'Wi-Fi mostly uses radio frequencies around 2.4 GHz and 5 GHz.'],
  ['What is the name of Microsoft\'s browser that replaced Internet Explorer?', 'Edge', 'Chrome', 'Safari', 'Firefox', 'Microsoft Edge launched in 2015, and Internet Explorer was retired in 2022.'],
  ['Which two digits does binary code use?', '0 and 1', '1 and 2', '0 and 9', '1 and 10', 'Binary is base 2. Each digit matches a tiny circuit being off (0) or on (1).'],
  ['Which company created the Windows operating system?', 'Microsoft', 'IBM', 'Apple', 'Intel', 'The first version, Windows 1.0, was released in 1985.'],
  ['What does "GPS" stand for?', 'Global Positioning System', 'General Positioning Service', 'Global Pinpoint Satellite', 'Geo Position Sensor', 'GPS works with a network of about 30 satellites operated by the US military.'],
  ['Which company owns Instagram?', 'Meta', 'Google', 'X (Twitter)', 'Snap', 'Facebook, now called Meta, bought Instagram in 2012 for about $1 billion.'],
  ['What does "USB" stand for?', 'Universal Serial Bus', 'United System Bus', 'Universal Signal Board', 'Unified Serial Bridge', 'USB arrived in 1996 to replace a jumble of different plugs. USB-C plugs work either way up.'],
  ['On Windows, which shortcut copies the selected item?', 'Ctrl + C', 'Ctrl + V', 'Ctrl + X', 'Ctrl + P', 'Ctrl + V pastes and Ctrl + X cuts. On a Mac, you use Cmd instead of Ctrl.'],
  ['Alan Turing is famous for helping crack which code during WWII?', 'Enigma', 'The Navajo code', 'Purple', 'The Zimmermann telegram', 'Turing worked at Bletchley Park, and his ideas also laid the foundations of modern computing and AI.'],
  ['What is "phishing"?', 'Tricking people into revealing sensitive information', 'A way to speed up the internet', 'A file compression method', 'A type of computer cooling', 'Phishing usually comes as fake emails or texts that look official and ask you to click a link or type a password.'],
  ['What does "PDF" stand for?', 'Portable Document Format', 'Printable Document File', 'Public Data Format', 'Portable Data File', 'Adobe created the PDF in 1993 so documents look the same on any device.'],
  ['Which company makes the Switch game console?', 'Nintendo', 'Sony', 'Sega', 'Microsoft', 'The Switch launched in 2017 and works both as a home console and as a handheld.'],
  ['What does "SSD" stand for?', 'Solid State Drive', 'Super Speed Disk', 'Secure Storage Device', 'System Software Drive', 'SSDs store data on memory chips with no moving parts, unlike spinning hard disk drives.'],
  ['Roughly when was the first network email sent?', '1971', '1985', '1991', '1962', 'Ray Tomlinson sent it in 1971 and picked the @ sign to separate the user\'s name from the computer\'s.'],
  ['Who co-founded Microsoft with Bill Gates?', 'Paul Allen', 'Steve Ballmer', 'Steve Wozniak', 'Larry Page', 'Gates and Allen, childhood friends, founded Microsoft in 1975 in Albuquerque, New Mexico.'],
  ['What does "HTML" stand for?', 'HyperText Markup Language', 'High Tech Modern Language', 'HyperText Machine Logic', 'Hyperlink Text Mode Language', 'HTML describes a page\'s structure: headings, paragraphs, links and images.'],
  ['What is the name of Apple\'s voice assistant?', 'Siri', 'Alexa', 'Cortana', 'Bixby', 'Siri arrived on the iPhone 4S in 2011. Alexa is Amazon\'s, Cortana Microsoft\'s and Bixby Samsung\'s.'],
  ['Which 1972 arcade game was the first big commercial video game hit?', 'Pong', 'Space Invaders', 'Pac-Man', 'Tetris', 'Pong, made by Atari, is a simple table-tennis game with two paddles and a ball.'],
  ['What does "LAN" stand for?', 'Local Area Network', 'Large Access Node', 'Linked Application Network', 'Long Area Network', 'A LAN links devices in one place, like a home or office. The internet links networks across the world.'],
  ['Who founded Google?', 'Larry Page and Sergey Brin', 'Bill Gates and Paul Allen', 'Steve Jobs and Steve Wozniak', 'Mark Zuckerberg and Eduardo Saverin', 'Page and Brin started Google in 1998 while they were PhD students at Stanford.'],
  ['Which language is mainly used to style web pages (colors, layout, fonts)?', 'CSS', 'HTML', 'SQL', 'PHP', 'CSS stands for Cascading Style Sheets. This game\'s look is written in CSS.'],
  ['Which language is used to query relational databases?', 'SQL', 'HTML', 'CSS', 'Swift', 'SQL stands for Structured Query Language and was developed at IBM in the 1970s.'],
  ['What does "IoT" stand for?', 'Internet of Things', 'Input or Transfer', 'Internal Operating Tool', 'Integrated Online Technology', 'IoT means everyday devices connected to the internet, like smart thermostats, doorbells and watches.'],
  ['In which year was Facebook launched?', '2004', '2001', '2006', '2008', 'Mark Zuckerberg launched it from his Harvard dorm room, at first only for Harvard students.'],
  ['Which company makes Galaxy smartphones?', 'Samsung', 'LG', 'Huawei', 'Sony', 'Samsung is a South Korean company founded in 1938, originally as a trading company.'],
  ['In programming, what is a "bug"?', 'An error in the code', 'A computer virus', 'A fast processor', 'A type of cable', 'The term is older, but in 1947 engineers famously found a real moth stuck inside the Harvard Mark II computer.'],
  ['Which company created ChatGPT?', 'OpenAI', 'Google', 'Microsoft', 'Meta', 'OpenAI released ChatGPT to the public in November 2022.'],
  ['What does "VPN" stand for?', 'Virtual Private Network', 'Very Protected Node', 'Verified Public Network', 'Virtual Protocol Number', 'A VPN encrypts your internet traffic and sends it through another server, hiding it from your local network.'],
  ['Ada Lovelace wrote what is often called the first computer program for which machine?', 'The Analytical Engine', 'The Enigma machine', 'ENIAC', 'The Colossus', 'Lovelace published her notes on Charles Babbage\'s machine in 1843. The programming language Ada is named after her.'],
  ['What does "QR" in QR code stand for?', 'Quick Response', 'Quality Reader', 'Query Result', 'Quantum Record', 'QR codes were invented in 1994 by Denso Wave in Japan to track car parts.'],
];
