export default [
  ['Which language has the most native speakers in the world?', 'Mandarin Chinese', 'English', 'Spanish', 'Hindi', 'Mandarin has close to a billion native speakers. Counting second-language speakers too, English has the most speakers overall.'],
  ['How many letters are in the English alphabet?', '26', '24', '25', '28', 'The English alphabet comes from the Latin alphabet used by the Romans.'],
  ['What is a word that reads the same backwards and forwards, like "level"?', 'A palindrome', 'An anagram', 'A homonym', 'An acronym', 'Famous palindromes include "racecar" and "A man, a plan, a canal: Panama".'],
  ['What is the official language of Brazil?', 'Portuguese', 'Spanish', 'French', 'English', 'Brazil was a Portuguese colony and is now the largest Portuguese-speaking country in the world.'],
  ['What does the Latin phrase "carpe diem" mean?', 'Seize the day', 'Live forever', 'Day by day', 'Fortune favors the bold', 'The phrase comes from the Roman poet Horace.'],
  ['What is a word with the opposite meaning of another called?', 'An antonym', 'A synonym', 'A homophone', 'A pseudonym', '"Hot" and "cold" are antonyms; "big" and "large" are synonyms.'],
  ['From which language does the word "kindergarten" come?', 'German', 'Dutch', 'Danish', 'Yiddish', 'It means "children\'s garden". Friedrich Fröbel coined it for the school he founded in Germany.'],
  ['Which of these languages is written in the Cyrillic alphabet?', 'Russian', 'Greek', 'Hungarian', 'Georgian', 'Cyrillic is also used for Ukrainian, Bulgarian, Serbian and other languages. Greek has its own alphabet.'],
  ['How many national languages does Switzerland have?', '4', '2', '3', '5', 'Switzerland\'s national languages are German, French, Italian and Romansh.'],
  ['What is an anagram?', 'A word made by rearranging the letters of another', 'A word that sounds like another', 'A word read the same backwards', 'A word formed from initials', '"Listen" is an anagram of "silent".'],
  ['What is the word for an extreme fear of spiders?', 'Arachnophobia', 'Agoraphobia', 'Claustrophobia', 'Acrophobia', 'From the Greek "arachne", spider. Claustrophobia is fear of tight spaces and acrophobia fear of heights.'],
  ['What does the abbreviation "e.g." stand for?', 'Exempli gratia ("for example")', 'Id est ("that is")', 'Et cetera ("and so on")', 'Ergo ("therefore")', 'People often mix them up: "e.g." gives examples, while "i.e." (id est) clarifies what you mean.'],
  ['What is the official language of Egypt?', 'Arabic', 'Coptic', 'French', 'English', 'Egyptian Arabic is one of the most widely understood Arabic dialects, thanks to Egyptian films and TV.'],
  ['What does the Japanese word "tsunami" literally mean?', 'Harbor wave', 'Big wave', 'Sea storm', 'Earth shake', '"Tsu" means harbor and "nami" means wave. Fishermen at sea often didn\'t notice the wave, then came back to wrecked harbors.'],
  ['What is a pseudonym?', 'A false name, like a pen name', 'A word with the same meaning', 'A grammar mistake', 'A short poem', 'George Orwell and Mark Twain are pseudonyms; their real names were Eric Blair and Samuel Clemens.'],
  ['Which is the most widely used writing system in the world?', 'The Latin alphabet', 'Cyrillic', 'Arabic script', 'Greek', 'The Latin alphabet is used for English, Spanish, French, Vietnamese, Turkish and many more.'],
  ['Flemish is a form of Dutch spoken in which country?', 'Belgium', 'Luxembourg', 'Denmark', 'Austria', 'Belgium has three official languages: Dutch, French and German.'],
  ['What does "RSVP" on an invitation stand for?', 'Répondez s\'il vous plaît', 'Reply soon, very pleased', 'Reserve seat via phone', 'Request special visitor pass', 'It\'s French for "please reply".'],
  ['Which punctuation mark shows possession, as in "Sam\'s book"?', 'Apostrophe', 'Comma', 'Colon', 'Hyphen', 'A classic trap: "it\'s" means "it is", while the possessive "its" has no apostrophe.'],
  ['Which language has the most native speakers in India?', 'Hindi', 'Bengali', 'Tamil', 'English', 'India recognizes 22 scheduled languages. Over 40% of Indians speak Hindi as their first language.'],
  ['What is a phrase like "break a leg", whose meaning isn\'t literal, called?', 'An idiom', 'A simile', 'A haiku', 'An oxymoron', '"Break a leg" means "good luck", usually said to performers before a show.'],
  ['Which language did the ancient Romans speak?', 'Latin', 'Greek', 'Italian', 'Etruscan', 'Latin evolved into the Romance languages: Italian, Spanish, French, Portuguese and Romanian.'],
  ['What is a simile?', 'A comparison using "like" or "as"', 'An exaggeration', 'A word that imitates a sound', 'A pair of contradictory words', '"As brave as a lion" is a simile; "he is a lion" is a metaphor.'],
  ['What is a word that imitates a sound, like "buzz" or "boom"?', 'Onomatopoeia', 'Alliteration', 'Hyperbole', 'Palindrome', 'Sounds differ by language: a rooster says "cock-a-doodle-doo" in English but "cocorico" in French.'],
  ['What is Esperanto?', 'A language invented in 1887', 'An old Spanish dialect', 'A form of sign language', 'A dialect of Italian', 'L. L. Zamenhof created Esperanto as an easy, neutral language for international communication.'],
  ['What is the official language of Austria?', 'German', 'Austrian', 'Hungarian', 'Czech', 'Austrian German has some words of its own, like "Jänner" for January.'],
  ['How many vowel letters are in the English alphabet, not counting Y?', '5', '4', '6', '7', 'A, E, I, O and U. Y sometimes acts as a vowel too, as in "gym".'],
  ['What is the only official language of the Canadian province of Quebec?', 'French', 'English', 'English and French', 'Inuktitut', 'Quebec made French its sole official language in 1977. Canada as a whole has two: English and French.'],
  ['What does Julius Caesar\'s phrase "veni, vidi, vici" mean?', 'I came, I saw, I conquered', 'I lived, I loved, I lost', 'I saw, I wanted, I took', 'I came, I fought, I won', 'Caesar reportedly wrote it after a lightning-fast victory at Zela in 47 BC.'],
  ['What does the Spanish word "hola" mean?', 'Hello', 'Goodbye', 'Thank you', 'Please', 'In Spanish, goodbye is "adiós", thank you is "gracias" and please is "por favor".'],
];
